-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity omp_reconstruction_omp_reconstruction_Pipeline_load_A_col is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln208 : IN STD_LOGIC_VECTOR (61 downto 0);
    A_local_47_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_47_ce0 : OUT STD_LOGIC;
    A_local_47_we0 : OUT STD_LOGIC;
    A_local_47_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_46_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_46_ce0 : OUT STD_LOGIC;
    A_local_46_we0 : OUT STD_LOGIC;
    A_local_46_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_45_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_45_ce0 : OUT STD_LOGIC;
    A_local_45_we0 : OUT STD_LOGIC;
    A_local_45_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_44_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_44_ce0 : OUT STD_LOGIC;
    A_local_44_we0 : OUT STD_LOGIC;
    A_local_44_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_43_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_43_ce0 : OUT STD_LOGIC;
    A_local_43_we0 : OUT STD_LOGIC;
    A_local_43_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_42_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_42_ce0 : OUT STD_LOGIC;
    A_local_42_we0 : OUT STD_LOGIC;
    A_local_42_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_41_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_41_ce0 : OUT STD_LOGIC;
    A_local_41_we0 : OUT STD_LOGIC;
    A_local_41_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_40_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_40_ce0 : OUT STD_LOGIC;
    A_local_40_we0 : OUT STD_LOGIC;
    A_local_40_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_39_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_39_ce0 : OUT STD_LOGIC;
    A_local_39_we0 : OUT STD_LOGIC;
    A_local_39_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_38_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_38_ce0 : OUT STD_LOGIC;
    A_local_38_we0 : OUT STD_LOGIC;
    A_local_38_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_37_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_37_ce0 : OUT STD_LOGIC;
    A_local_37_we0 : OUT STD_LOGIC;
    A_local_37_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_36_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_36_ce0 : OUT STD_LOGIC;
    A_local_36_we0 : OUT STD_LOGIC;
    A_local_36_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_35_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_35_ce0 : OUT STD_LOGIC;
    A_local_35_we0 : OUT STD_LOGIC;
    A_local_35_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_34_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_34_ce0 : OUT STD_LOGIC;
    A_local_34_we0 : OUT STD_LOGIC;
    A_local_34_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_33_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_33_ce0 : OUT STD_LOGIC;
    A_local_33_we0 : OUT STD_LOGIC;
    A_local_33_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_32_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_32_ce0 : OUT STD_LOGIC;
    A_local_32_we0 : OUT STD_LOGIC;
    A_local_32_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_31_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_31_ce0 : OUT STD_LOGIC;
    A_local_31_we0 : OUT STD_LOGIC;
    A_local_31_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_30_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_30_ce0 : OUT STD_LOGIC;
    A_local_30_we0 : OUT STD_LOGIC;
    A_local_30_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_29_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_29_ce0 : OUT STD_LOGIC;
    A_local_29_we0 : OUT STD_LOGIC;
    A_local_29_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_28_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_28_ce0 : OUT STD_LOGIC;
    A_local_28_we0 : OUT STD_LOGIC;
    A_local_28_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_27_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_27_ce0 : OUT STD_LOGIC;
    A_local_27_we0 : OUT STD_LOGIC;
    A_local_27_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_26_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_26_ce0 : OUT STD_LOGIC;
    A_local_26_we0 : OUT STD_LOGIC;
    A_local_26_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_25_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_25_ce0 : OUT STD_LOGIC;
    A_local_25_we0 : OUT STD_LOGIC;
    A_local_25_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_24_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_24_ce0 : OUT STD_LOGIC;
    A_local_24_we0 : OUT STD_LOGIC;
    A_local_24_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_23_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_23_ce0 : OUT STD_LOGIC;
    A_local_23_we0 : OUT STD_LOGIC;
    A_local_23_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_22_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_22_ce0 : OUT STD_LOGIC;
    A_local_22_we0 : OUT STD_LOGIC;
    A_local_22_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_21_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_21_ce0 : OUT STD_LOGIC;
    A_local_21_we0 : OUT STD_LOGIC;
    A_local_21_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_20_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_20_ce0 : OUT STD_LOGIC;
    A_local_20_we0 : OUT STD_LOGIC;
    A_local_20_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_19_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_19_ce0 : OUT STD_LOGIC;
    A_local_19_we0 : OUT STD_LOGIC;
    A_local_19_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_18_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_18_ce0 : OUT STD_LOGIC;
    A_local_18_we0 : OUT STD_LOGIC;
    A_local_18_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_17_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_17_ce0 : OUT STD_LOGIC;
    A_local_17_we0 : OUT STD_LOGIC;
    A_local_17_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_16_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_16_ce0 : OUT STD_LOGIC;
    A_local_16_we0 : OUT STD_LOGIC;
    A_local_16_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_15_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_15_ce0 : OUT STD_LOGIC;
    A_local_15_we0 : OUT STD_LOGIC;
    A_local_15_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_14_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_14_ce0 : OUT STD_LOGIC;
    A_local_14_we0 : OUT STD_LOGIC;
    A_local_14_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_13_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_13_ce0 : OUT STD_LOGIC;
    A_local_13_we0 : OUT STD_LOGIC;
    A_local_13_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_12_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_12_ce0 : OUT STD_LOGIC;
    A_local_12_we0 : OUT STD_LOGIC;
    A_local_12_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_11_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_11_ce0 : OUT STD_LOGIC;
    A_local_11_we0 : OUT STD_LOGIC;
    A_local_11_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_10_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_10_ce0 : OUT STD_LOGIC;
    A_local_10_we0 : OUT STD_LOGIC;
    A_local_10_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_9_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_9_ce0 : OUT STD_LOGIC;
    A_local_9_we0 : OUT STD_LOGIC;
    A_local_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_8_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_8_ce0 : OUT STD_LOGIC;
    A_local_8_we0 : OUT STD_LOGIC;
    A_local_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_7_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_7_ce0 : OUT STD_LOGIC;
    A_local_7_we0 : OUT STD_LOGIC;
    A_local_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_6_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_6_ce0 : OUT STD_LOGIC;
    A_local_6_we0 : OUT STD_LOGIC;
    A_local_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_5_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_5_ce0 : OUT STD_LOGIC;
    A_local_5_we0 : OUT STD_LOGIC;
    A_local_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_4_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_4_ce0 : OUT STD_LOGIC;
    A_local_4_we0 : OUT STD_LOGIC;
    A_local_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_3_ce0 : OUT STD_LOGIC;
    A_local_3_we0 : OUT STD_LOGIC;
    A_local_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_2_ce0 : OUT STD_LOGIC;
    A_local_2_we0 : OUT STD_LOGIC;
    A_local_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_1_ce0 : OUT STD_LOGIC;
    A_local_1_we0 : OUT STD_LOGIC;
    A_local_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_local_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_local_ce0 : OUT STD_LOGIC;
    A_local_we0 : OUT STD_LOGIC;
    A_local_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    i_1 : IN STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of omp_reconstruction_omp_reconstruction_Pipeline_load_A_col is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv6_2E : STD_LOGIC_VECTOR (5 downto 0) := "101110";
    constant ap_const_lv6_2D : STD_LOGIC_VECTOR (5 downto 0) := "101101";
    constant ap_const_lv6_2C : STD_LOGIC_VECTOR (5 downto 0) := "101100";
    constant ap_const_lv6_2B : STD_LOGIC_VECTOR (5 downto 0) := "101011";
    constant ap_const_lv6_2A : STD_LOGIC_VECTOR (5 downto 0) := "101010";
    constant ap_const_lv6_29 : STD_LOGIC_VECTOR (5 downto 0) := "101001";
    constant ap_const_lv6_28 : STD_LOGIC_VECTOR (5 downto 0) := "101000";
    constant ap_const_lv6_27 : STD_LOGIC_VECTOR (5 downto 0) := "100111";
    constant ap_const_lv6_26 : STD_LOGIC_VECTOR (5 downto 0) := "100110";
    constant ap_const_lv6_25 : STD_LOGIC_VECTOR (5 downto 0) := "100101";
    constant ap_const_lv6_24 : STD_LOGIC_VECTOR (5 downto 0) := "100100";
    constant ap_const_lv6_23 : STD_LOGIC_VECTOR (5 downto 0) := "100011";
    constant ap_const_lv6_22 : STD_LOGIC_VECTOR (5 downto 0) := "100010";
    constant ap_const_lv6_21 : STD_LOGIC_VECTOR (5 downto 0) := "100001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1F : STD_LOGIC_VECTOR (5 downto 0) := "011111";
    constant ap_const_lv6_1E : STD_LOGIC_VECTOR (5 downto 0) := "011110";
    constant ap_const_lv6_1D : STD_LOGIC_VECTOR (5 downto 0) := "011101";
    constant ap_const_lv6_1C : STD_LOGIC_VECTOR (5 downto 0) := "011100";
    constant ap_const_lv6_1B : STD_LOGIC_VECTOR (5 downto 0) := "011011";
    constant ap_const_lv6_1A : STD_LOGIC_VECTOR (5 downto 0) := "011010";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv6_18 : STD_LOGIC_VECTOR (5 downto 0) := "011000";
    constant ap_const_lv6_17 : STD_LOGIC_VECTOR (5 downto 0) := "010111";
    constant ap_const_lv6_16 : STD_LOGIC_VECTOR (5 downto 0) := "010110";
    constant ap_const_lv6_15 : STD_LOGIC_VECTOR (5 downto 0) := "010101";
    constant ap_const_lv6_14 : STD_LOGIC_VECTOR (5 downto 0) := "010100";
    constant ap_const_lv6_13 : STD_LOGIC_VECTOR (5 downto 0) := "010011";
    constant ap_const_lv6_12 : STD_LOGIC_VECTOR (5 downto 0) := "010010";
    constant ap_const_lv6_11 : STD_LOGIC_VECTOR (5 downto 0) := "010001";
    constant ap_const_lv6_10 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_const_lv6_F : STD_LOGIC_VECTOR (5 downto 0) := "001111";
    constant ap_const_lv6_E : STD_LOGIC_VECTOR (5 downto 0) := "001110";
    constant ap_const_lv6_D : STD_LOGIC_VECTOR (5 downto 0) := "001101";
    constant ap_const_lv6_C : STD_LOGIC_VECTOR (5 downto 0) := "001100";
    constant ap_const_lv6_B : STD_LOGIC_VECTOR (5 downto 0) := "001011";
    constant ap_const_lv6_A : STD_LOGIC_VECTOR (5 downto 0) := "001010";
    constant ap_const_lv6_9 : STD_LOGIC_VECTOR (5 downto 0) := "001001";
    constant ap_const_lv6_8 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_const_lv6_7 : STD_LOGIC_VECTOR (5 downto 0) := "000111";
    constant ap_const_lv6_6 : STD_LOGIC_VECTOR (5 downto 0) := "000110";
    constant ap_const_lv6_5 : STD_LOGIC_VECTOR (5 downto 0) := "000101";
    constant ap_const_lv6_4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_const_lv6_3 : STD_LOGIC_VECTOR (5 downto 0) := "000011";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_3E : STD_LOGIC_VECTOR (5 downto 0) := "111110";
    constant ap_const_lv6_3D : STD_LOGIC_VECTOR (5 downto 0) := "111101";
    constant ap_const_lv6_3C : STD_LOGIC_VECTOR (5 downto 0) := "111100";
    constant ap_const_lv6_3B : STD_LOGIC_VECTOR (5 downto 0) := "111011";
    constant ap_const_lv6_3A : STD_LOGIC_VECTOR (5 downto 0) := "111010";
    constant ap_const_lv6_39 : STD_LOGIC_VECTOR (5 downto 0) := "111001";
    constant ap_const_lv6_38 : STD_LOGIC_VECTOR (5 downto 0) := "111000";
    constant ap_const_lv6_37 : STD_LOGIC_VECTOR (5 downto 0) := "110111";
    constant ap_const_lv6_36 : STD_LOGIC_VECTOR (5 downto 0) := "110110";
    constant ap_const_lv6_35 : STD_LOGIC_VECTOR (5 downto 0) := "110101";
    constant ap_const_lv6_34 : STD_LOGIC_VECTOR (5 downto 0) := "110100";
    constant ap_const_lv6_33 : STD_LOGIC_VECTOR (5 downto 0) := "110011";
    constant ap_const_lv6_32 : STD_LOGIC_VECTOR (5 downto 0) := "110010";
    constant ap_const_lv6_31 : STD_LOGIC_VECTOR (5 downto 0) := "110001";
    constant ap_const_lv6_30 : STD_LOGIC_VECTOR (5 downto 0) := "110000";
    constant ap_const_lv6_2F : STD_LOGIC_VECTOR (5 downto 0) := "101111";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln209_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln209_fu_897_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem1_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_1_read_reg_982 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal j_1_reg_991 : STD_LOGIC_VECTOR (7 downto 0);
    signal j_1_reg_991_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal bitcast_ln211_fu_920_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln211_reg_1000 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal zext_ln209_fu_924_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_240 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln209_fu_903_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component omp_reconstruction_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component omp_reconstruction_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    j_fu_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln209_fu_897_p2 = ap_const_lv1_0))) then 
                    j_fu_240 <= add_ln209_fu_903_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_240 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln209_reg_996 <= icmp_ln209_fu_897_p2;
                j_1_reg_991 <= ap_sig_allocacmp_j_1;
                j_1_reg_991_pp0_iter1_reg <= j_1_reg_991;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln209_reg_996 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                bitcast_ln211_reg_1000 <= bitcast_ln211_fu_920_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    A_local_10_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_10_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_10_ce0 <= ap_const_logic_1;
        else 
            A_local_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_10_d0 <= bitcast_ln211_reg_1000;

    A_local_10_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_A) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_10_we0 <= ap_const_logic_1;
        else 
            A_local_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_11_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_11_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_11_ce0 <= ap_const_logic_1;
        else 
            A_local_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_11_d0 <= bitcast_ln211_reg_1000;

    A_local_11_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_B) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_11_we0 <= ap_const_logic_1;
        else 
            A_local_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_12_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_12_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_12_ce0 <= ap_const_logic_1;
        else 
            A_local_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_12_d0 <= bitcast_ln211_reg_1000;

    A_local_12_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_C) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_12_we0 <= ap_const_logic_1;
        else 
            A_local_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_13_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_13_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_13_ce0 <= ap_const_logic_1;
        else 
            A_local_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_13_d0 <= bitcast_ln211_reg_1000;

    A_local_13_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_D) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_13_we0 <= ap_const_logic_1;
        else 
            A_local_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_14_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_14_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_14_ce0 <= ap_const_logic_1;
        else 
            A_local_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_14_d0 <= bitcast_ln211_reg_1000;

    A_local_14_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_E) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_14_we0 <= ap_const_logic_1;
        else 
            A_local_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_15_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_15_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_15_ce0 <= ap_const_logic_1;
        else 
            A_local_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_15_d0 <= bitcast_ln211_reg_1000;

    A_local_15_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_F) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_15_we0 <= ap_const_logic_1;
        else 
            A_local_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_16_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_16_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_16_ce0 <= ap_const_logic_1;
        else 
            A_local_16_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_16_d0 <= bitcast_ln211_reg_1000;

    A_local_16_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_10) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_16_we0 <= ap_const_logic_1;
        else 
            A_local_16_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_17_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_17_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_17_ce0 <= ap_const_logic_1;
        else 
            A_local_17_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_17_d0 <= bitcast_ln211_reg_1000;

    A_local_17_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_11) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_17_we0 <= ap_const_logic_1;
        else 
            A_local_17_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_18_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_18_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_18_ce0 <= ap_const_logic_1;
        else 
            A_local_18_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_18_d0 <= bitcast_ln211_reg_1000;

    A_local_18_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_12) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_18_we0 <= ap_const_logic_1;
        else 
            A_local_18_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_19_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_19_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_19_ce0 <= ap_const_logic_1;
        else 
            A_local_19_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_19_d0 <= bitcast_ln211_reg_1000;

    A_local_19_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_13) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_19_we0 <= ap_const_logic_1;
        else 
            A_local_19_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_1_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_1_ce0 <= ap_const_logic_1;
        else 
            A_local_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_1_d0 <= bitcast_ln211_reg_1000;

    A_local_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_1_we0 <= ap_const_logic_1;
        else 
            A_local_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_20_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_20_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_20_ce0 <= ap_const_logic_1;
        else 
            A_local_20_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_20_d0 <= bitcast_ln211_reg_1000;

    A_local_20_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_14) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_20_we0 <= ap_const_logic_1;
        else 
            A_local_20_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_21_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_21_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_21_ce0 <= ap_const_logic_1;
        else 
            A_local_21_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_21_d0 <= bitcast_ln211_reg_1000;

    A_local_21_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_15) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_21_we0 <= ap_const_logic_1;
        else 
            A_local_21_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_22_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_22_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_22_ce0 <= ap_const_logic_1;
        else 
            A_local_22_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_22_d0 <= bitcast_ln211_reg_1000;

    A_local_22_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_16) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_22_we0 <= ap_const_logic_1;
        else 
            A_local_22_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_23_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_23_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_23_ce0 <= ap_const_logic_1;
        else 
            A_local_23_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_23_d0 <= bitcast_ln211_reg_1000;

    A_local_23_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_17) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_23_we0 <= ap_const_logic_1;
        else 
            A_local_23_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_24_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_24_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_24_ce0 <= ap_const_logic_1;
        else 
            A_local_24_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_24_d0 <= bitcast_ln211_reg_1000;

    A_local_24_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_18) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_24_we0 <= ap_const_logic_1;
        else 
            A_local_24_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_25_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_25_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_25_ce0 <= ap_const_logic_1;
        else 
            A_local_25_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_25_d0 <= bitcast_ln211_reg_1000;

    A_local_25_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_19) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_25_we0 <= ap_const_logic_1;
        else 
            A_local_25_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_26_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_26_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_26_ce0 <= ap_const_logic_1;
        else 
            A_local_26_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_26_d0 <= bitcast_ln211_reg_1000;

    A_local_26_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_1A) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_26_we0 <= ap_const_logic_1;
        else 
            A_local_26_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_27_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_27_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_27_ce0 <= ap_const_logic_1;
        else 
            A_local_27_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_27_d0 <= bitcast_ln211_reg_1000;

    A_local_27_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_1B) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_27_we0 <= ap_const_logic_1;
        else 
            A_local_27_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_28_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_28_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_28_ce0 <= ap_const_logic_1;
        else 
            A_local_28_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_28_d0 <= bitcast_ln211_reg_1000;

    A_local_28_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_1C) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_28_we0 <= ap_const_logic_1;
        else 
            A_local_28_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_29_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_29_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_29_ce0 <= ap_const_logic_1;
        else 
            A_local_29_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_29_d0 <= bitcast_ln211_reg_1000;

    A_local_29_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_1D) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_29_we0 <= ap_const_logic_1;
        else 
            A_local_29_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_2_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_2_ce0 <= ap_const_logic_1;
        else 
            A_local_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_2_d0 <= bitcast_ln211_reg_1000;

    A_local_2_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_2_we0 <= ap_const_logic_1;
        else 
            A_local_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_30_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_30_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_30_ce0 <= ap_const_logic_1;
        else 
            A_local_30_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_30_d0 <= bitcast_ln211_reg_1000;

    A_local_30_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_1E) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_30_we0 <= ap_const_logic_1;
        else 
            A_local_30_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_31_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_31_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_31_ce0 <= ap_const_logic_1;
        else 
            A_local_31_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_31_d0 <= bitcast_ln211_reg_1000;

    A_local_31_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_1F) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_31_we0 <= ap_const_logic_1;
        else 
            A_local_31_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_32_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_32_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_32_ce0 <= ap_const_logic_1;
        else 
            A_local_32_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_32_d0 <= bitcast_ln211_reg_1000;

    A_local_32_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_20) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_32_we0 <= ap_const_logic_1;
        else 
            A_local_32_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_33_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_33_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_33_ce0 <= ap_const_logic_1;
        else 
            A_local_33_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_33_d0 <= bitcast_ln211_reg_1000;

    A_local_33_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_21) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_33_we0 <= ap_const_logic_1;
        else 
            A_local_33_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_34_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_34_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_34_ce0 <= ap_const_logic_1;
        else 
            A_local_34_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_34_d0 <= bitcast_ln211_reg_1000;

    A_local_34_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_22) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_34_we0 <= ap_const_logic_1;
        else 
            A_local_34_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_35_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_35_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_35_ce0 <= ap_const_logic_1;
        else 
            A_local_35_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_35_d0 <= bitcast_ln211_reg_1000;

    A_local_35_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_23) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_35_we0 <= ap_const_logic_1;
        else 
            A_local_35_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_36_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_36_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_36_ce0 <= ap_const_logic_1;
        else 
            A_local_36_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_36_d0 <= bitcast_ln211_reg_1000;

    A_local_36_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_24) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_36_we0 <= ap_const_logic_1;
        else 
            A_local_36_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_37_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_37_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_37_ce0 <= ap_const_logic_1;
        else 
            A_local_37_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_37_d0 <= bitcast_ln211_reg_1000;

    A_local_37_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_25) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_37_we0 <= ap_const_logic_1;
        else 
            A_local_37_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_38_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_38_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_38_ce0 <= ap_const_logic_1;
        else 
            A_local_38_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_38_d0 <= bitcast_ln211_reg_1000;

    A_local_38_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_26) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_38_we0 <= ap_const_logic_1;
        else 
            A_local_38_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_39_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_39_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_39_ce0 <= ap_const_logic_1;
        else 
            A_local_39_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_39_d0 <= bitcast_ln211_reg_1000;

    A_local_39_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_27) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_39_we0 <= ap_const_logic_1;
        else 
            A_local_39_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_3_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_3_ce0 <= ap_const_logic_1;
        else 
            A_local_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_3_d0 <= bitcast_ln211_reg_1000;

    A_local_3_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_3_we0 <= ap_const_logic_1;
        else 
            A_local_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_40_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_40_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_40_ce0 <= ap_const_logic_1;
        else 
            A_local_40_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_40_d0 <= bitcast_ln211_reg_1000;

    A_local_40_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_28) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_40_we0 <= ap_const_logic_1;
        else 
            A_local_40_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_41_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_41_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_41_ce0 <= ap_const_logic_1;
        else 
            A_local_41_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_41_d0 <= bitcast_ln211_reg_1000;

    A_local_41_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_29) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_41_we0 <= ap_const_logic_1;
        else 
            A_local_41_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_42_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_42_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_42_ce0 <= ap_const_logic_1;
        else 
            A_local_42_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_42_d0 <= bitcast_ln211_reg_1000;

    A_local_42_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_2A) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_42_we0 <= ap_const_logic_1;
        else 
            A_local_42_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_43_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_43_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_43_ce0 <= ap_const_logic_1;
        else 
            A_local_43_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_43_d0 <= bitcast_ln211_reg_1000;

    A_local_43_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_2B) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_43_we0 <= ap_const_logic_1;
        else 
            A_local_43_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_44_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_44_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_44_ce0 <= ap_const_logic_1;
        else 
            A_local_44_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_44_d0 <= bitcast_ln211_reg_1000;

    A_local_44_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_2C) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_44_we0 <= ap_const_logic_1;
        else 
            A_local_44_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_45_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_45_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_45_ce0 <= ap_const_logic_1;
        else 
            A_local_45_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_45_d0 <= bitcast_ln211_reg_1000;

    A_local_45_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_2D) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_45_we0 <= ap_const_logic_1;
        else 
            A_local_45_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_46_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_46_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_46_ce0 <= ap_const_logic_1;
        else 
            A_local_46_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_46_d0 <= bitcast_ln211_reg_1000;

    A_local_46_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_2E) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_46_we0 <= ap_const_logic_1;
        else 
            A_local_46_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_47_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_47_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_47_ce0 <= ap_const_logic_1;
        else 
            A_local_47_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_47_d0 <= bitcast_ln211_reg_1000;

    A_local_47_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((i_1_read_reg_982 = ap_const_lv6_2F) or ((i_1_read_reg_982 = ap_const_lv6_30) or ((i_1_read_reg_982 = ap_const_lv6_31) or ((i_1_read_reg_982 = ap_const_lv6_32) or ((i_1_read_reg_982 = ap_const_lv6_33) or ((i_1_read_reg_982 = ap_const_lv6_34) or ((i_1_read_reg_982 = ap_const_lv6_35) or ((i_1_read_reg_982 = ap_const_lv6_36) or ((i_1_read_reg_982 = ap_const_lv6_37) or ((i_1_read_reg_982 = ap_const_lv6_38) or ((i_1_read_reg_982 = ap_const_lv6_39) or ((i_1_read_reg_982 = ap_const_lv6_3A) or ((i_1_read_reg_982 = ap_const_lv6_3B) or ((i_1_read_reg_982 = ap_const_lv6_3C) or ((i_1_read_reg_982 = ap_const_lv6_3D) or ((i_1_read_reg_982 = ap_const_lv6_3E) or (i_1_read_reg_982 = ap_const_lv6_3F))))))))))))))))))) then 
            A_local_47_we0 <= ap_const_logic_1;
        else 
            A_local_47_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_4_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_4_ce0 <= ap_const_logic_1;
        else 
            A_local_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_4_d0 <= bitcast_ln211_reg_1000;

    A_local_4_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_4) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_4_we0 <= ap_const_logic_1;
        else 
            A_local_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_5_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_5_ce0 <= ap_const_logic_1;
        else 
            A_local_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_5_d0 <= bitcast_ln211_reg_1000;

    A_local_5_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_5) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_5_we0 <= ap_const_logic_1;
        else 
            A_local_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_6_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_6_ce0 <= ap_const_logic_1;
        else 
            A_local_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_6_d0 <= bitcast_ln211_reg_1000;

    A_local_6_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_6) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_6_we0 <= ap_const_logic_1;
        else 
            A_local_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_7_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_7_ce0 <= ap_const_logic_1;
        else 
            A_local_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_7_d0 <= bitcast_ln211_reg_1000;

    A_local_7_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_7) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_7_we0 <= ap_const_logic_1;
        else 
            A_local_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_8_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_8_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_8_ce0 <= ap_const_logic_1;
        else 
            A_local_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_8_d0 <= bitcast_ln211_reg_1000;

    A_local_8_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_8) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_8_we0 <= ap_const_logic_1;
        else 
            A_local_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_9_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_9_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_9_ce0 <= ap_const_logic_1;
        else 
            A_local_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_9_d0 <= bitcast_ln211_reg_1000;

    A_local_9_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_9) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_9_we0 <= ap_const_logic_1;
        else 
            A_local_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_address0 <= zext_ln209_fu_924_p1(7 - 1 downto 0);

    A_local_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_ce0 <= ap_const_logic_1;
        else 
            A_local_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_local_d0 <= bitcast_ln211_reg_1000;

    A_local_we0_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_read_reg_982, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (i_1_read_reg_982 = ap_const_lv6_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_local_we0 <= ap_const_logic_1;
        else 
            A_local_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln209_fu_903_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(ap_const_lv8_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem1_RVALID, icmp_ln209_reg_996)
    begin
                ap_block_pp0_stage0_11001 <= ((icmp_ln209_reg_996 = ap_const_lv1_0) and (m_axi_gmem1_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem1_RVALID, icmp_ln209_reg_996)
    begin
                ap_block_pp0_stage0_subdone <= ((icmp_ln209_reg_996 = ap_const_lv1_0) and (m_axi_gmem1_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_gmem1_RVALID, icmp_ln209_reg_996)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln209_reg_996 = ap_const_lv1_0) and (m_axi_gmem1_RVALID = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln209_fu_897_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln209_fu_897_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln209_reg_996, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln209_reg_996 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_240, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_240;
        end if; 
    end process;

    bitcast_ln211_fu_920_p1 <= m_axi_gmem1_RDATA;

    gmem1_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem1_RVALID, icmp_ln209_reg_996, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln209_reg_996 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem1_blk_n_R <= m_axi_gmem1_RVALID;
        else 
            gmem1_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    i_1_read_reg_982 <= i_1;
    icmp_ln209_fu_897_p2 <= "1" when (ap_sig_allocacmp_j_1 = ap_const_lv8_80) else "0";
    m_axi_gmem1_ARADDR <= ap_const_lv64_0;
    m_axi_gmem1_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_ARID <= ap_const_lv1_0;
    m_axi_gmem1_ARLEN <= ap_const_lv32_0;
    m_axi_gmem1_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_ARUSER <= ap_const_lv1_0;
    m_axi_gmem1_ARVALID <= ap_const_logic_0;
    m_axi_gmem1_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_AWID <= ap_const_lv1_0;
    m_axi_gmem1_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_BREADY <= ap_const_logic_0;

    m_axi_gmem1_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln209_reg_996, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln209_reg_996 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_gmem1_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_WDATA <= ap_const_lv32_0;
    m_axi_gmem1_WID <= ap_const_lv1_0;
    m_axi_gmem1_WLAST <= ap_const_logic_0;
    m_axi_gmem1_WSTRB <= ap_const_lv4_0;
    m_axi_gmem1_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_WVALID <= ap_const_logic_0;
    zext_ln209_fu_924_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_1_reg_991_pp0_iter1_reg),64));
end behav;
