-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity omp_reconstruction_omp_reconstruction_Pipeline_mult_theta is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    G_inv_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_8_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_16_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_24_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_32_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_40_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_48_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_56_load : IN STD_LOGIC_VECTOR (31 downto 0);
    b_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_1_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_9_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_17_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_25_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_33_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_41_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_49_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_57_load : IN STD_LOGIC_VECTOR (31 downto 0);
    b_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_2_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_10_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_18_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_26_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_34_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_42_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_50_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_58_load : IN STD_LOGIC_VECTOR (31 downto 0);
    b_2_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_3_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_11_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_19_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_27_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_35_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_43_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_51_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_59_load : IN STD_LOGIC_VECTOR (31 downto 0);
    b_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_4_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_12_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_20_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_28_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_36_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_44_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_52_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_60_load : IN STD_LOGIC_VECTOR (31 downto 0);
    b_4_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_5_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_13_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_21_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_29_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_37_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_45_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_53_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_61_load : IN STD_LOGIC_VECTOR (31 downto 0);
    b_5_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_6_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_14_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_22_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_30_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_38_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_46_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_54_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_62_load : IN STD_LOGIC_VECTOR (31 downto 0);
    b_6_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_7_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_15_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_23_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_31_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_39_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_47_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_55_load : IN STD_LOGIC_VECTOR (31 downto 0);
    G_inv_63_load : IN STD_LOGIC_VECTOR (31 downto 0);
    b_7_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    theta_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    theta_ce0 : OUT STD_LOGIC;
    theta_we0 : OUT STD_LOGIC;
    theta_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4359_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4359_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4359_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_4359_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4359_p_ce : OUT STD_LOGIC;
    grp_fu_4363_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4363_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4363_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_4363_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4363_p_ce : OUT STD_LOGIC;
    grp_fu_4367_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4367_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4367_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_4367_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4367_p_ce : OUT STD_LOGIC;
    grp_fu_4371_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4371_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4371_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_4371_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4371_p_ce : OUT STD_LOGIC;
    grp_fu_4375_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4375_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4375_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_4375_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4375_p_ce : OUT STD_LOGIC;
    grp_fu_4379_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4379_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4379_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_4379_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4379_p_ce : OUT STD_LOGIC;
    grp_fu_4383_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4383_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4383_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_4383_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4383_p_ce : OUT STD_LOGIC;
    grp_fu_4387_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4387_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4387_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_4387_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4387_p_ce : OUT STD_LOGIC;
    grp_fu_4551_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4551_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4551_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4551_p_ce : OUT STD_LOGIC;
    grp_fu_4555_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4555_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4555_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4555_p_ce : OUT STD_LOGIC;
    grp_fu_4559_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4559_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4559_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4559_p_ce : OUT STD_LOGIC;
    grp_fu_4563_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4563_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4563_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4563_p_ce : OUT STD_LOGIC;
    grp_fu_4567_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4567_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4567_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4567_p_ce : OUT STD_LOGIC;
    grp_fu_4571_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4571_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4571_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4571_p_ce : OUT STD_LOGIC;
    grp_fu_4575_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4575_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4575_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4575_p_ce : OUT STD_LOGIC;
    grp_fu_4579_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4579_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4579_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_4579_p_ce : OUT STD_LOGIC );
end;


architecture behav of omp_reconstruction_omp_reconstruction_Pipeline_mult_theta is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln294_fu_700_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_1_reg_1173 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter8_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter9_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter10_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter11_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter12_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter13_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter14_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter15_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_1173_pp0_iter16_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln296_fu_712_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln296_reg_1182 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln296_reg_1182_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln296_reg_1182_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln296_reg_1182_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln296_reg_1182_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln296_reg_1182_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln296_reg_1182_pp0_iter6_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln296_reg_1182_pp0_iter7_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln296_reg_1182_pp0_iter8_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln296_reg_1182_pp0_iter9_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln296_reg_1182_pp0_iter10_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln296_reg_1182_pp0_iter11_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln296_reg_1182_pp0_iter12_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln296_reg_1182_pp0_iter13_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_5_fu_716_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul1_reg_1198 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_744_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_reg_1208 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul198_1_reg_1213 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_758_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_reg_1223 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul198_2_reg_1228 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_772_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_2_reg_1238 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul198_3_reg_1243 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_786_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_reg_1253 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul198_4_reg_1258 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_800_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_4_reg_1268 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul198_5_reg_1273 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_814_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_5_reg_1283 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul198_6_reg_1288 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_828_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_6_reg_1298 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul198_7_reg_1303 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln294_fu_842_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_176 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln294_fu_706_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_716_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component omp_reconstruction_faddfsub_32ns_32ns_32_2_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component omp_reconstruction_fmul_32ns_32ns_32_2_max_dsp_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component omp_reconstruction_mux_8_3_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component omp_reconstruction_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_8_3_32_1_1_U1753 : component omp_reconstruction_mux_8_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => G_inv_load,
        din1 => G_inv_8_load,
        din2 => G_inv_16_load,
        din3 => G_inv_24_load,
        din4 => G_inv_32_load,
        din5 => G_inv_40_load,
        din6 => G_inv_48_load,
        din7 => G_inv_56_load,
        din8 => tmp_5_fu_716_p9,
        dout => tmp_5_fu_716_p10);

    mux_8_3_32_1_1_U1754 : component omp_reconstruction_mux_8_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => G_inv_1_load,
        din1 => G_inv_9_load,
        din2 => G_inv_17_load,
        din3 => G_inv_25_load,
        din4 => G_inv_33_load,
        din5 => G_inv_41_load,
        din6 => G_inv_49_load,
        din7 => G_inv_57_load,
        din8 => trunc_ln296_reg_1182_pp0_iter1_reg,
        dout => tmp_6_fu_744_p10);

    mux_8_3_32_1_1_U1755 : component omp_reconstruction_mux_8_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => G_inv_2_load,
        din1 => G_inv_10_load,
        din2 => G_inv_18_load,
        din3 => G_inv_26_load,
        din4 => G_inv_34_load,
        din5 => G_inv_42_load,
        din6 => G_inv_50_load,
        din7 => G_inv_58_load,
        din8 => trunc_ln296_reg_1182_pp0_iter3_reg,
        dout => tmp_7_fu_758_p10);

    mux_8_3_32_1_1_U1756 : component omp_reconstruction_mux_8_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => G_inv_3_load,
        din1 => G_inv_11_load,
        din2 => G_inv_19_load,
        din3 => G_inv_27_load,
        din4 => G_inv_35_load,
        din5 => G_inv_43_load,
        din6 => G_inv_51_load,
        din7 => G_inv_59_load,
        din8 => trunc_ln296_reg_1182_pp0_iter5_reg,
        dout => tmp_8_fu_772_p10);

    mux_8_3_32_1_1_U1757 : component omp_reconstruction_mux_8_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => G_inv_4_load,
        din1 => G_inv_12_load,
        din2 => G_inv_20_load,
        din3 => G_inv_28_load,
        din4 => G_inv_36_load,
        din5 => G_inv_44_load,
        din6 => G_inv_52_load,
        din7 => G_inv_60_load,
        din8 => trunc_ln296_reg_1182_pp0_iter7_reg,
        dout => tmp_9_fu_786_p10);

    mux_8_3_32_1_1_U1758 : component omp_reconstruction_mux_8_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => G_inv_5_load,
        din1 => G_inv_13_load,
        din2 => G_inv_21_load,
        din3 => G_inv_29_load,
        din4 => G_inv_37_load,
        din5 => G_inv_45_load,
        din6 => G_inv_53_load,
        din7 => G_inv_61_load,
        din8 => trunc_ln296_reg_1182_pp0_iter9_reg,
        dout => tmp_s_fu_800_p10);

    mux_8_3_32_1_1_U1759 : component omp_reconstruction_mux_8_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => G_inv_6_load,
        din1 => G_inv_14_load,
        din2 => G_inv_22_load,
        din3 => G_inv_30_load,
        din4 => G_inv_38_load,
        din5 => G_inv_46_load,
        din6 => G_inv_54_load,
        din7 => G_inv_62_load,
        din8 => trunc_ln296_reg_1182_pp0_iter11_reg,
        dout => tmp_1_fu_814_p10);

    mux_8_3_32_1_1_U1760 : component omp_reconstruction_mux_8_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => G_inv_7_load,
        din1 => G_inv_15_load,
        din2 => G_inv_23_load,
        din3 => G_inv_31_load,
        din4 => G_inv_39_load,
        din5 => G_inv_47_load,
        din6 => G_inv_55_load,
        din7 => G_inv_63_load,
        din8 => trunc_ln296_reg_1182_pp0_iter13_reg,
        dout => tmp_3_fu_828_p10);

    flow_control_loop_pipe_sequential_init_U : component omp_reconstruction_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_fu_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln294_fu_700_p2 = ap_const_lv1_0))) then 
                    i_fu_176 <= add_ln294_fu_706_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_176 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                i_1_reg_1173_pp0_iter10_reg <= i_1_reg_1173_pp0_iter9_reg;
                i_1_reg_1173_pp0_iter11_reg <= i_1_reg_1173_pp0_iter10_reg;
                i_1_reg_1173_pp0_iter12_reg <= i_1_reg_1173_pp0_iter11_reg;
                i_1_reg_1173_pp0_iter13_reg <= i_1_reg_1173_pp0_iter12_reg;
                i_1_reg_1173_pp0_iter14_reg <= i_1_reg_1173_pp0_iter13_reg;
                i_1_reg_1173_pp0_iter15_reg <= i_1_reg_1173_pp0_iter14_reg;
                i_1_reg_1173_pp0_iter16_reg <= i_1_reg_1173_pp0_iter15_reg;
                i_1_reg_1173_pp0_iter2_reg <= i_1_reg_1173_pp0_iter1_reg;
                i_1_reg_1173_pp0_iter3_reg <= i_1_reg_1173_pp0_iter2_reg;
                i_1_reg_1173_pp0_iter4_reg <= i_1_reg_1173_pp0_iter3_reg;
                i_1_reg_1173_pp0_iter5_reg <= i_1_reg_1173_pp0_iter4_reg;
                i_1_reg_1173_pp0_iter6_reg <= i_1_reg_1173_pp0_iter5_reg;
                i_1_reg_1173_pp0_iter7_reg <= i_1_reg_1173_pp0_iter6_reg;
                i_1_reg_1173_pp0_iter8_reg <= i_1_reg_1173_pp0_iter7_reg;
                i_1_reg_1173_pp0_iter9_reg <= i_1_reg_1173_pp0_iter8_reg;
                mul198_1_reg_1213 <= grp_fu_4555_p_dout0;
                mul198_2_reg_1228 <= grp_fu_4559_p_dout0;
                mul198_3_reg_1243 <= grp_fu_4563_p_dout0;
                mul198_4_reg_1258 <= grp_fu_4567_p_dout0;
                mul198_5_reg_1273 <= grp_fu_4571_p_dout0;
                mul198_6_reg_1288 <= grp_fu_4575_p_dout0;
                mul198_7_reg_1303 <= grp_fu_4579_p_dout0;
                sum_1_reg_1223 <= grp_fu_4363_p_dout0;
                sum_2_reg_1238 <= grp_fu_4367_p_dout0;
                sum_3_reg_1253 <= grp_fu_4371_p_dout0;
                sum_4_reg_1268 <= grp_fu_4375_p_dout0;
                sum_5_reg_1283 <= grp_fu_4379_p_dout0;
                sum_6_reg_1298 <= grp_fu_4383_p_dout0;
                sum_reg_1208 <= grp_fu_4359_p_dout0;
                trunc_ln296_reg_1182_pp0_iter10_reg <= trunc_ln296_reg_1182_pp0_iter9_reg;
                trunc_ln296_reg_1182_pp0_iter11_reg <= trunc_ln296_reg_1182_pp0_iter10_reg;
                trunc_ln296_reg_1182_pp0_iter12_reg <= trunc_ln296_reg_1182_pp0_iter11_reg;
                trunc_ln296_reg_1182_pp0_iter13_reg <= trunc_ln296_reg_1182_pp0_iter12_reg;
                trunc_ln296_reg_1182_pp0_iter2_reg <= trunc_ln296_reg_1182_pp0_iter1_reg;
                trunc_ln296_reg_1182_pp0_iter3_reg <= trunc_ln296_reg_1182_pp0_iter2_reg;
                trunc_ln296_reg_1182_pp0_iter4_reg <= trunc_ln296_reg_1182_pp0_iter3_reg;
                trunc_ln296_reg_1182_pp0_iter5_reg <= trunc_ln296_reg_1182_pp0_iter4_reg;
                trunc_ln296_reg_1182_pp0_iter6_reg <= trunc_ln296_reg_1182_pp0_iter5_reg;
                trunc_ln296_reg_1182_pp0_iter7_reg <= trunc_ln296_reg_1182_pp0_iter6_reg;
                trunc_ln296_reg_1182_pp0_iter8_reg <= trunc_ln296_reg_1182_pp0_iter7_reg;
                trunc_ln296_reg_1182_pp0_iter9_reg <= trunc_ln296_reg_1182_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                i_1_reg_1173 <= ap_sig_allocacmp_i_1;
                i_1_reg_1173_pp0_iter1_reg <= i_1_reg_1173;
                mul1_reg_1198 <= grp_fu_4551_p_dout0;
                trunc_ln296_reg_1182_pp0_iter1_reg <= trunc_ln296_reg_1182;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln294_fu_700_p2 = ap_const_lv1_0))) then
                trunc_ln296_reg_1182 <= trunc_ln296_fu_712_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln294_fu_706_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln294_fu_700_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln294_fu_700_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter16_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17)
    begin
        if (((ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_176, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_176;
        end if; 
    end process;

    grp_fu_4359_p_ce <= ap_const_logic_1;
    grp_fu_4359_p_din0 <= mul1_reg_1198;
    grp_fu_4359_p_din1 <= ap_const_lv32_0;
    grp_fu_4359_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_4363_p_ce <= ap_const_logic_1;
    grp_fu_4363_p_din0 <= sum_reg_1208;
    grp_fu_4363_p_din1 <= mul198_1_reg_1213;
    grp_fu_4363_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_4367_p_ce <= ap_const_logic_1;
    grp_fu_4367_p_din0 <= sum_1_reg_1223;
    grp_fu_4367_p_din1 <= mul198_2_reg_1228;
    grp_fu_4367_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_4371_p_ce <= ap_const_logic_1;
    grp_fu_4371_p_din0 <= sum_2_reg_1238;
    grp_fu_4371_p_din1 <= mul198_3_reg_1243;
    grp_fu_4371_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_4375_p_ce <= ap_const_logic_1;
    grp_fu_4375_p_din0 <= sum_3_reg_1253;
    grp_fu_4375_p_din1 <= mul198_4_reg_1258;
    grp_fu_4375_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_4379_p_ce <= ap_const_logic_1;
    grp_fu_4379_p_din0 <= sum_4_reg_1268;
    grp_fu_4379_p_din1 <= mul198_5_reg_1273;
    grp_fu_4379_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_4383_p_ce <= ap_const_logic_1;
    grp_fu_4383_p_din0 <= sum_5_reg_1283;
    grp_fu_4383_p_din1 <= mul198_6_reg_1288;
    grp_fu_4383_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_4387_p_ce <= ap_const_logic_1;
    grp_fu_4387_p_din0 <= sum_6_reg_1298;
    grp_fu_4387_p_din1 <= mul198_7_reg_1303;
    grp_fu_4387_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_4551_p_ce <= ap_const_logic_1;
    grp_fu_4551_p_din0 <= tmp_5_fu_716_p10;
    grp_fu_4551_p_din1 <= b_reload;
    grp_fu_4555_p_ce <= ap_const_logic_1;
    grp_fu_4555_p_din0 <= tmp_6_fu_744_p10;
    grp_fu_4555_p_din1 <= b_1_reload;
    grp_fu_4559_p_ce <= ap_const_logic_1;
    grp_fu_4559_p_din0 <= tmp_7_fu_758_p10;
    grp_fu_4559_p_din1 <= b_2_reload;
    grp_fu_4563_p_ce <= ap_const_logic_1;
    grp_fu_4563_p_din0 <= tmp_8_fu_772_p10;
    grp_fu_4563_p_din1 <= b_3_reload;
    grp_fu_4567_p_ce <= ap_const_logic_1;
    grp_fu_4567_p_din0 <= tmp_9_fu_786_p10;
    grp_fu_4567_p_din1 <= b_4_reload;
    grp_fu_4571_p_ce <= ap_const_logic_1;
    grp_fu_4571_p_din0 <= tmp_s_fu_800_p10;
    grp_fu_4571_p_din1 <= b_5_reload;
    grp_fu_4575_p_ce <= ap_const_logic_1;
    grp_fu_4575_p_din0 <= tmp_1_fu_814_p10;
    grp_fu_4575_p_din1 <= b_6_reload;
    grp_fu_4579_p_ce <= ap_const_logic_1;
    grp_fu_4579_p_din0 <= tmp_3_fu_828_p10;
    grp_fu_4579_p_din1 <= b_7_reload;
    icmp_ln294_fu_700_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv4_8) else "0";
    theta_address0 <= zext_ln294_fu_842_p1(3 - 1 downto 0);

    theta_ce0_assign_proc : process(ap_enable_reg_pp0_iter17, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter17 = ap_const_logic_1))) then 
            theta_ce0 <= ap_const_logic_1;
        else 
            theta_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    theta_d0 <= grp_fu_4387_p_dout0;

    theta_we0_assign_proc : process(ap_enable_reg_pp0_iter17, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter17 = ap_const_logic_1))) then 
            theta_we0 <= ap_const_logic_1;
        else 
            theta_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_5_fu_716_p9 <= ap_sig_allocacmp_i_1(3 - 1 downto 0);
    trunc_ln296_fu_712_p1 <= ap_sig_allocacmp_i_1(3 - 1 downto 0);
    zext_ln294_fu_842_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_reg_1173_pp0_iter16_reg),64));
end behav;
