-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity omp_reconstruction_acd_inversion_Pipeline_inv_d_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    D : IN STD_LOGIC_VECTOR (31 downto 0);
    D_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    D_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    D_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    D_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    D_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    D_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    D_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    D_inv_7_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    D_inv_7_out_ap_vld : OUT STD_LOGIC;
    D_inv_6_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    D_inv_6_out_ap_vld : OUT STD_LOGIC;
    D_inv_5_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    D_inv_5_out_ap_vld : OUT STD_LOGIC;
    D_inv_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    D_inv_4_out_ap_vld : OUT STD_LOGIC;
    D_inv_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    D_inv_3_out_ap_vld : OUT STD_LOGIC;
    D_inv_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    D_inv_2_out_ap_vld : OUT STD_LOGIC;
    D_inv_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    D_inv_1_out_ap_vld : OUT STD_LOGIC;
    D_inv_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    D_inv_out_ap_vld : OUT STD_LOGIC;
    grp_fu_3300_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_3300_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_3300_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_3300_p_ce : OUT STD_LOGIC );
end;


architecture behav of omp_reconstruction_acd_inversion_Pipeline_inv_d_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv32_3F800000 : STD_LOGIC_VECTOR (31 downto 0) := "00111111100000000000000000000000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln143_fu_229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln143_reg_400 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln143_reg_400_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln143_reg_400_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln143_reg_400_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln143_fu_241_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln143_reg_404 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln143_reg_404_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln143_reg_404_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln143_reg_404_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln143_reg_404_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_245_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_8_fu_76 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln143_fu_235_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal D_inv_fu_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal D_inv_1_fu_84 : STD_LOGIC_VECTOR (31 downto 0);
    signal D_inv_2_fu_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal D_inv_3_fu_92 : STD_LOGIC_VECTOR (31 downto 0);
    signal D_inv_4_fu_96 : STD_LOGIC_VECTOR (31 downto 0);
    signal D_inv_5_fu_100 : STD_LOGIC_VECTOR (31 downto 0);
    signal D_inv_6_fu_104 : STD_LOGIC_VECTOR (31 downto 0);
    signal D_inv_7_fu_108 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_s_fu_245_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component omp_reconstruction_fdiv_32ns_32ns_32_6_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component omp_reconstruction_mux_8_3_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component omp_reconstruction_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_8_3_32_1_1_U1116 : component omp_reconstruction_mux_8_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => D,
        din1 => D_1,
        din2 => D_2,
        din3 => D_3,
        din4 => D_4,
        din5 => D_5,
        din6 => D_6,
        din7 => D_7,
        din8 => tmp_s_fu_245_p9,
        dout => tmp_s_fu_245_p10);

    flow_control_loop_pipe_sequential_init_U : component omp_reconstruction_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    i_8_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln143_fu_229_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_8_fu_76 <= add_ln143_fu_235_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_8_fu_76 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (trunc_ln143_reg_404_pp0_iter4_reg = ap_const_lv3_1))) then
                D_inv_1_fu_84 <= grp_fu_3300_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (trunc_ln143_reg_404_pp0_iter4_reg = ap_const_lv3_2))) then
                D_inv_2_fu_88 <= grp_fu_3300_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (trunc_ln143_reg_404_pp0_iter4_reg = ap_const_lv3_3))) then
                D_inv_3_fu_92 <= grp_fu_3300_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (trunc_ln143_reg_404_pp0_iter4_reg = ap_const_lv3_4))) then
                D_inv_4_fu_96 <= grp_fu_3300_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (trunc_ln143_reg_404_pp0_iter4_reg = ap_const_lv3_5))) then
                D_inv_5_fu_100 <= grp_fu_3300_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (trunc_ln143_reg_404_pp0_iter4_reg = ap_const_lv3_6))) then
                D_inv_6_fu_104 <= grp_fu_3300_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (trunc_ln143_reg_404_pp0_iter4_reg = ap_const_lv3_7))) then
                D_inv_7_fu_108 <= grp_fu_3300_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (trunc_ln143_reg_404_pp0_iter4_reg = ap_const_lv3_0))) then
                D_inv_fu_80 <= grp_fu_3300_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln143_reg_400 <= icmp_ln143_fu_229_p2;
                icmp_ln143_reg_400_pp0_iter1_reg <= icmp_ln143_reg_400;
                trunc_ln143_reg_404_pp0_iter1_reg <= trunc_ln143_reg_404;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                icmp_ln143_reg_400_pp0_iter2_reg <= icmp_ln143_reg_400_pp0_iter1_reg;
                icmp_ln143_reg_400_pp0_iter3_reg <= icmp_ln143_reg_400_pp0_iter2_reg;
                trunc_ln143_reg_404_pp0_iter2_reg <= trunc_ln143_reg_404_pp0_iter1_reg;
                trunc_ln143_reg_404_pp0_iter3_reg <= trunc_ln143_reg_404_pp0_iter2_reg;
                trunc_ln143_reg_404_pp0_iter4_reg <= trunc_ln143_reg_404_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln143_fu_229_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln143_reg_404 <= trunc_ln143_fu_241_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    D_inv_1_out <= D_inv_1_fu_84;

    D_inv_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln143_reg_400_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln143_reg_400_pp0_iter3_reg = ap_const_lv1_1))) then 
            D_inv_1_out_ap_vld <= ap_const_logic_1;
        else 
            D_inv_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    D_inv_2_out <= D_inv_2_fu_88;

    D_inv_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln143_reg_400_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln143_reg_400_pp0_iter3_reg = ap_const_lv1_1))) then 
            D_inv_2_out_ap_vld <= ap_const_logic_1;
        else 
            D_inv_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    D_inv_3_out <= D_inv_3_fu_92;

    D_inv_3_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln143_reg_400_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln143_reg_400_pp0_iter3_reg = ap_const_lv1_1))) then 
            D_inv_3_out_ap_vld <= ap_const_logic_1;
        else 
            D_inv_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    D_inv_4_out <= D_inv_4_fu_96;

    D_inv_4_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln143_reg_400_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln143_reg_400_pp0_iter3_reg = ap_const_lv1_1))) then 
            D_inv_4_out_ap_vld <= ap_const_logic_1;
        else 
            D_inv_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    D_inv_5_out <= D_inv_5_fu_100;

    D_inv_5_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln143_reg_400_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln143_reg_400_pp0_iter3_reg = ap_const_lv1_1))) then 
            D_inv_5_out_ap_vld <= ap_const_logic_1;
        else 
            D_inv_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    D_inv_6_out <= D_inv_6_fu_104;

    D_inv_6_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln143_reg_400_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln143_reg_400_pp0_iter3_reg = ap_const_lv1_1))) then 
            D_inv_6_out_ap_vld <= ap_const_logic_1;
        else 
            D_inv_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    D_inv_7_out <= D_inv_7_fu_108;

    D_inv_7_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln143_reg_400_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln143_reg_400_pp0_iter3_reg = ap_const_lv1_1))) then 
            D_inv_7_out_ap_vld <= ap_const_logic_1;
        else 
            D_inv_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    D_inv_out <= D_inv_fu_80;

    D_inv_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln143_reg_400_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln143_reg_400_pp0_iter3_reg = ap_const_lv1_1))) then 
            D_inv_out_ap_vld <= ap_const_logic_1;
        else 
            D_inv_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln143_fu_235_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln143_fu_229_p2)
    begin
        if (((icmp_ln143_fu_229_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, i_8_fu_76, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i <= i_8_fu_76;
        end if; 
    end process;

    grp_fu_3300_p_ce <= ap_const_logic_1;
    grp_fu_3300_p_din0 <= ap_const_lv32_3F800000;
    grp_fu_3300_p_din1 <= tmp_s_fu_245_p10;
    icmp_ln143_fu_229_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv4_8) else "0";
    tmp_s_fu_245_p9 <= ap_sig_allocacmp_i(3 - 1 downto 0);
    trunc_ln143_fu_241_p1 <= ap_sig_allocacmp_i(3 - 1 downto 0);
end behav;
