// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module omp_reconstruction_acd_inversion_Pipeline_calc_T (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        D_inv_reload,
        D_inv_1_reload,
        D_inv_2_reload,
        D_inv_3_reload,
        D_inv_4_reload,
        D_inv_5_reload,
        D_inv_6_reload,
        D_inv_7_reload,
        mux_case_09029_reload,
        L_inv_load,
        L_inv_1_load,
        L_inv_2_load,
        L_inv_3_load,
        L_inv_4_load,
        L_inv_5_load,
        L_inv_6_load,
        mux_case_010632_reload,
        L_inv_load_1,
        L_inv_1_load_1,
        L_inv_2_load_1,
        L_inv_3_load_1,
        L_inv_4_load_1,
        L_inv_5_load_1,
        L_inv_6_load_1,
        mux_case_012235_reload,
        L_inv_load_2,
        L_inv_1_load_2,
        L_inv_2_load_2,
        L_inv_3_load_2,
        L_inv_4_load_2,
        L_inv_5_load_2,
        L_inv_6_load_2,
        mux_case_013838_reload,
        L_inv_load_3,
        L_inv_1_load_3,
        L_inv_2_load_3,
        L_inv_3_load_3,
        L_inv_4_load_3,
        L_inv_5_load_3,
        L_inv_6_load_3,
        mux_case_015441_reload,
        L_inv_load_4,
        L_inv_1_load_4,
        L_inv_2_load_4,
        L_inv_3_load_4,
        L_inv_4_load_4,
        L_inv_5_load_4,
        L_inv_6_load_4,
        mux_case_017044_reload,
        L_inv_load_5,
        L_inv_1_load_5,
        L_inv_2_load_5,
        L_inv_3_load_5,
        L_inv_4_load_5,
        L_inv_5_load_5,
        L_inv_6_load_5,
        mux_case_018647_reload,
        L_inv_load_6,
        L_inv_1_load_6,
        L_inv_2_load_6,
        L_inv_3_load_6,
        L_inv_4_load_6,
        L_inv_5_load_6,
        L_inv_6_load_6,
        mux_case_020250_reload,
        L_inv_load_7,
        L_inv_1_load_7,
        L_inv_2_load_7,
        L_inv_3_load_7,
        L_inv_4_load_7,
        L_inv_5_load_7,
        L_inv_6_load_7,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        p_out2,
        p_out2_ap_vld,
        p_out3,
        p_out3_ap_vld,
        p_out4,
        p_out4_ap_vld,
        p_out5,
        p_out5_ap_vld,
        p_out6,
        p_out6_ap_vld,
        p_out7,
        p_out7_ap_vld,
        p_out8,
        p_out8_ap_vld,
        p_out9,
        p_out9_ap_vld,
        p_out10,
        p_out10_ap_vld,
        p_out11,
        p_out11_ap_vld,
        p_out12,
        p_out12_ap_vld,
        p_out13,
        p_out13_ap_vld,
        p_out14,
        p_out14_ap_vld,
        p_out15,
        p_out15_ap_vld,
        p_out16,
        p_out16_ap_vld,
        p_out17,
        p_out17_ap_vld,
        p_out18,
        p_out18_ap_vld,
        p_out19,
        p_out19_ap_vld,
        p_out20,
        p_out20_ap_vld,
        p_out21,
        p_out21_ap_vld,
        p_out22,
        p_out22_ap_vld,
        p_out23,
        p_out23_ap_vld,
        p_out24,
        p_out24_ap_vld,
        p_out25,
        p_out25_ap_vld,
        p_out26,
        p_out26_ap_vld,
        p_out27,
        p_out27_ap_vld,
        p_out28,
        p_out28_ap_vld,
        p_out29,
        p_out29_ap_vld,
        p_out30,
        p_out30_ap_vld,
        p_out31,
        p_out31_ap_vld,
        p_out32,
        p_out32_ap_vld,
        p_out33,
        p_out33_ap_vld,
        p_out34,
        p_out34_ap_vld,
        p_out35,
        p_out35_ap_vld,
        p_out36,
        p_out36_ap_vld,
        p_out37,
        p_out37_ap_vld,
        p_out38,
        p_out38_ap_vld,
        p_out39,
        p_out39_ap_vld,
        p_out40,
        p_out40_ap_vld,
        p_out41,
        p_out41_ap_vld,
        p_out42,
        p_out42_ap_vld,
        p_out43,
        p_out43_ap_vld,
        p_out44,
        p_out44_ap_vld,
        p_out45,
        p_out45_ap_vld,
        p_out46,
        p_out46_ap_vld,
        p_out47,
        p_out47_ap_vld,
        p_out48,
        p_out48_ap_vld,
        p_out49,
        p_out49_ap_vld,
        p_out50,
        p_out50_ap_vld,
        p_out51,
        p_out51_ap_vld,
        p_out52,
        p_out52_ap_vld,
        p_out53,
        p_out53_ap_vld,
        p_out54,
        p_out54_ap_vld,
        p_out55,
        p_out55_ap_vld,
        p_out56,
        p_out56_ap_vld,
        p_out57,
        p_out57_ap_vld,
        p_out58,
        p_out58_ap_vld,
        p_out59,
        p_out59_ap_vld,
        p_out60,
        p_out60_ap_vld,
        p_out61,
        p_out61_ap_vld,
        p_out62,
        p_out62_ap_vld,
        p_out63,
        p_out63_ap_vld,
        grp_fu_3283_p_din0,
        grp_fu_3283_p_din1,
        grp_fu_3283_p_dout0,
        grp_fu_3283_p_ce,
        grp_fu_3287_p_din0,
        grp_fu_3287_p_din1,
        grp_fu_3287_p_dout0,
        grp_fu_3287_p_ce,
        grp_fu_8251_p_din0,
        grp_fu_8251_p_din1,
        grp_fu_8251_p_dout0,
        grp_fu_8251_p_ce,
        grp_fu_8255_p_din0,
        grp_fu_8255_p_din1,
        grp_fu_8255_p_dout0,
        grp_fu_8255_p_ce,
        grp_fu_8259_p_din0,
        grp_fu_8259_p_din1,
        grp_fu_8259_p_dout0,
        grp_fu_8259_p_ce,
        grp_fu_8263_p_din0,
        grp_fu_8263_p_din1,
        grp_fu_8263_p_dout0,
        grp_fu_8263_p_ce,
        grp_fu_8267_p_din0,
        grp_fu_8267_p_din1,
        grp_fu_8267_p_dout0,
        grp_fu_8267_p_ce,
        grp_fu_8271_p_din0,
        grp_fu_8271_p_din1,
        grp_fu_8271_p_dout0,
        grp_fu_8271_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] D_inv_reload;
input  [31:0] D_inv_1_reload;
input  [31:0] D_inv_2_reload;
input  [31:0] D_inv_3_reload;
input  [31:0] D_inv_4_reload;
input  [31:0] D_inv_5_reload;
input  [31:0] D_inv_6_reload;
input  [31:0] D_inv_7_reload;
input  [31:0] mux_case_09029_reload;
input  [31:0] L_inv_load;
input  [31:0] L_inv_1_load;
input  [31:0] L_inv_2_load;
input  [31:0] L_inv_3_load;
input  [31:0] L_inv_4_load;
input  [31:0] L_inv_5_load;
input  [31:0] L_inv_6_load;
input  [31:0] mux_case_010632_reload;
input  [31:0] L_inv_load_1;
input  [31:0] L_inv_1_load_1;
input  [31:0] L_inv_2_load_1;
input  [31:0] L_inv_3_load_1;
input  [31:0] L_inv_4_load_1;
input  [31:0] L_inv_5_load_1;
input  [31:0] L_inv_6_load_1;
input  [31:0] mux_case_012235_reload;
input  [31:0] L_inv_load_2;
input  [31:0] L_inv_1_load_2;
input  [31:0] L_inv_2_load_2;
input  [31:0] L_inv_3_load_2;
input  [31:0] L_inv_4_load_2;
input  [31:0] L_inv_5_load_2;
input  [31:0] L_inv_6_load_2;
input  [31:0] mux_case_013838_reload;
input  [31:0] L_inv_load_3;
input  [31:0] L_inv_1_load_3;
input  [31:0] L_inv_2_load_3;
input  [31:0] L_inv_3_load_3;
input  [31:0] L_inv_4_load_3;
input  [31:0] L_inv_5_load_3;
input  [31:0] L_inv_6_load_3;
input  [31:0] mux_case_015441_reload;
input  [31:0] L_inv_load_4;
input  [31:0] L_inv_1_load_4;
input  [31:0] L_inv_2_load_4;
input  [31:0] L_inv_3_load_4;
input  [31:0] L_inv_4_load_4;
input  [31:0] L_inv_5_load_4;
input  [31:0] L_inv_6_load_4;
input  [31:0] mux_case_017044_reload;
input  [31:0] L_inv_load_5;
input  [31:0] L_inv_1_load_5;
input  [31:0] L_inv_2_load_5;
input  [31:0] L_inv_3_load_5;
input  [31:0] L_inv_4_load_5;
input  [31:0] L_inv_5_load_5;
input  [31:0] L_inv_6_load_5;
input  [31:0] mux_case_018647_reload;
input  [31:0] L_inv_load_6;
input  [31:0] L_inv_1_load_6;
input  [31:0] L_inv_2_load_6;
input  [31:0] L_inv_3_load_6;
input  [31:0] L_inv_4_load_6;
input  [31:0] L_inv_5_load_6;
input  [31:0] L_inv_6_load_6;
input  [31:0] mux_case_020250_reload;
input  [31:0] L_inv_load_7;
input  [31:0] L_inv_1_load_7;
input  [31:0] L_inv_2_load_7;
input  [31:0] L_inv_3_load_7;
input  [31:0] L_inv_4_load_7;
input  [31:0] L_inv_5_load_7;
input  [31:0] L_inv_6_load_7;
output  [31:0] p_out;
output   p_out_ap_vld;
output  [31:0] p_out1;
output   p_out1_ap_vld;
output  [31:0] p_out2;
output   p_out2_ap_vld;
output  [31:0] p_out3;
output   p_out3_ap_vld;
output  [31:0] p_out4;
output   p_out4_ap_vld;
output  [31:0] p_out5;
output   p_out5_ap_vld;
output  [31:0] p_out6;
output   p_out6_ap_vld;
output  [31:0] p_out7;
output   p_out7_ap_vld;
output  [31:0] p_out8;
output   p_out8_ap_vld;
output  [31:0] p_out9;
output   p_out9_ap_vld;
output  [31:0] p_out10;
output   p_out10_ap_vld;
output  [31:0] p_out11;
output   p_out11_ap_vld;
output  [31:0] p_out12;
output   p_out12_ap_vld;
output  [31:0] p_out13;
output   p_out13_ap_vld;
output  [31:0] p_out14;
output   p_out14_ap_vld;
output  [31:0] p_out15;
output   p_out15_ap_vld;
output  [31:0] p_out16;
output   p_out16_ap_vld;
output  [31:0] p_out17;
output   p_out17_ap_vld;
output  [31:0] p_out18;
output   p_out18_ap_vld;
output  [31:0] p_out19;
output   p_out19_ap_vld;
output  [31:0] p_out20;
output   p_out20_ap_vld;
output  [31:0] p_out21;
output   p_out21_ap_vld;
output  [31:0] p_out22;
output   p_out22_ap_vld;
output  [31:0] p_out23;
output   p_out23_ap_vld;
output  [31:0] p_out24;
output   p_out24_ap_vld;
output  [31:0] p_out25;
output   p_out25_ap_vld;
output  [31:0] p_out26;
output   p_out26_ap_vld;
output  [31:0] p_out27;
output   p_out27_ap_vld;
output  [31:0] p_out28;
output   p_out28_ap_vld;
output  [31:0] p_out29;
output   p_out29_ap_vld;
output  [31:0] p_out30;
output   p_out30_ap_vld;
output  [31:0] p_out31;
output   p_out31_ap_vld;
output  [31:0] p_out32;
output   p_out32_ap_vld;
output  [31:0] p_out33;
output   p_out33_ap_vld;
output  [31:0] p_out34;
output   p_out34_ap_vld;
output  [31:0] p_out35;
output   p_out35_ap_vld;
output  [31:0] p_out36;
output   p_out36_ap_vld;
output  [31:0] p_out37;
output   p_out37_ap_vld;
output  [31:0] p_out38;
output   p_out38_ap_vld;
output  [31:0] p_out39;
output   p_out39_ap_vld;
output  [31:0] p_out40;
output   p_out40_ap_vld;
output  [31:0] p_out41;
output   p_out41_ap_vld;
output  [31:0] p_out42;
output   p_out42_ap_vld;
output  [31:0] p_out43;
output   p_out43_ap_vld;
output  [31:0] p_out44;
output   p_out44_ap_vld;
output  [31:0] p_out45;
output   p_out45_ap_vld;
output  [31:0] p_out46;
output   p_out46_ap_vld;
output  [31:0] p_out47;
output   p_out47_ap_vld;
output  [31:0] p_out48;
output   p_out48_ap_vld;
output  [31:0] p_out49;
output   p_out49_ap_vld;
output  [31:0] p_out50;
output   p_out50_ap_vld;
output  [31:0] p_out51;
output   p_out51_ap_vld;
output  [31:0] p_out52;
output   p_out52_ap_vld;
output  [31:0] p_out53;
output   p_out53_ap_vld;
output  [31:0] p_out54;
output   p_out54_ap_vld;
output  [31:0] p_out55;
output   p_out55_ap_vld;
output  [31:0] p_out56;
output   p_out56_ap_vld;
output  [31:0] p_out57;
output   p_out57_ap_vld;
output  [31:0] p_out58;
output   p_out58_ap_vld;
output  [31:0] p_out59;
output   p_out59_ap_vld;
output  [31:0] p_out60;
output   p_out60_ap_vld;
output  [31:0] p_out61;
output   p_out61_ap_vld;
output  [31:0] p_out62;
output   p_out62_ap_vld;
output  [31:0] p_out63;
output   p_out63_ap_vld;
output  [31:0] grp_fu_3283_p_din0;
output  [31:0] grp_fu_3283_p_din1;
input  [31:0] grp_fu_3283_p_dout0;
output   grp_fu_3283_p_ce;
output  [31:0] grp_fu_3287_p_din0;
output  [31:0] grp_fu_3287_p_din1;
input  [31:0] grp_fu_3287_p_dout0;
output   grp_fu_3287_p_ce;
output  [31:0] grp_fu_8251_p_din0;
output  [31:0] grp_fu_8251_p_din1;
input  [31:0] grp_fu_8251_p_dout0;
output   grp_fu_8251_p_ce;
output  [31:0] grp_fu_8255_p_din0;
output  [31:0] grp_fu_8255_p_din1;
input  [31:0] grp_fu_8255_p_dout0;
output   grp_fu_8255_p_ce;
output  [31:0] grp_fu_8259_p_din0;
output  [31:0] grp_fu_8259_p_din1;
input  [31:0] grp_fu_8259_p_dout0;
output   grp_fu_8259_p_ce;
output  [31:0] grp_fu_8263_p_din0;
output  [31:0] grp_fu_8263_p_din1;
input  [31:0] grp_fu_8263_p_dout0;
output   grp_fu_8263_p_ce;
output  [31:0] grp_fu_8267_p_din0;
output  [31:0] grp_fu_8267_p_din1;
input  [31:0] grp_fu_8267_p_dout0;
output   grp_fu_8267_p_ce;
output  [31:0] grp_fu_8271_p_din0;
output  [31:0] grp_fu_8271_p_din1;
input  [31:0] grp_fu_8271_p_dout0;
output   grp_fu_8271_p_ce;

reg ap_idle;
reg p_out_ap_vld;
reg p_out1_ap_vld;
reg p_out2_ap_vld;
reg p_out3_ap_vld;
reg p_out4_ap_vld;
reg p_out5_ap_vld;
reg p_out6_ap_vld;
reg p_out7_ap_vld;
reg p_out8_ap_vld;
reg p_out9_ap_vld;
reg p_out10_ap_vld;
reg p_out11_ap_vld;
reg p_out12_ap_vld;
reg p_out13_ap_vld;
reg p_out14_ap_vld;
reg p_out15_ap_vld;
reg p_out16_ap_vld;
reg p_out17_ap_vld;
reg p_out18_ap_vld;
reg p_out19_ap_vld;
reg p_out20_ap_vld;
reg p_out21_ap_vld;
reg p_out22_ap_vld;
reg p_out23_ap_vld;
reg p_out24_ap_vld;
reg p_out25_ap_vld;
reg p_out26_ap_vld;
reg p_out27_ap_vld;
reg p_out28_ap_vld;
reg p_out29_ap_vld;
reg p_out30_ap_vld;
reg p_out31_ap_vld;
reg p_out32_ap_vld;
reg p_out33_ap_vld;
reg p_out34_ap_vld;
reg p_out35_ap_vld;
reg p_out36_ap_vld;
reg p_out37_ap_vld;
reg p_out38_ap_vld;
reg p_out39_ap_vld;
reg p_out40_ap_vld;
reg p_out41_ap_vld;
reg p_out42_ap_vld;
reg p_out43_ap_vld;
reg p_out44_ap_vld;
reg p_out45_ap_vld;
reg p_out46_ap_vld;
reg p_out47_ap_vld;
reg p_out48_ap_vld;
reg p_out49_ap_vld;
reg p_out50_ap_vld;
reg p_out51_ap_vld;
reg p_out52_ap_vld;
reg p_out53_ap_vld;
reg p_out54_ap_vld;
reg p_out55_ap_vld;
reg p_out56_ap_vld;
reg p_out57_ap_vld;
reg p_out58_ap_vld;
reg p_out59_ap_vld;
reg p_out60_ap_vld;
reg p_out61_ap_vld;
reg p_out62_ap_vld;
reg p_out63_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln162_fu_1494_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] trunc_ln162_fu_1506_p1;
reg   [2:0] trunc_ln162_reg_2699;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] tmp_8_fu_1510_p10;
wire   [31:0] tmp_9_fu_1540_p10;
wire   [31:0] tmp_1_fu_1563_p10;
wire   [31:0] tmp_2_fu_1586_p10;
wire   [31:0] tmp_3_fu_1609_p10;
wire   [31:0] tmp_s_fu_1632_p10;
wire   [31:0] tmp_4_fu_1655_p10;
wire   [31:0] tmp_5_fu_1678_p10;
wire   [31:0] tmp_6_fu_1701_p10;
reg   [3:0] i_fu_314;
wire   [3:0] add_ln162_fu_1500_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_10;
wire    ap_block_pp0_stage0;
reg   [31:0] empty_fu_318;
reg   [31:0] empty_239_fu_322;
reg   [31:0] empty_240_fu_326;
reg   [31:0] empty_241_fu_330;
reg   [31:0] empty_242_fu_334;
reg   [31:0] empty_243_fu_338;
reg   [31:0] empty_244_fu_342;
reg   [31:0] empty_245_fu_346;
reg   [31:0] empty_246_fu_350;
reg   [31:0] empty_247_fu_354;
reg   [31:0] empty_248_fu_358;
reg   [31:0] empty_249_fu_362;
reg   [31:0] empty_250_fu_366;
reg   [31:0] empty_251_fu_370;
reg   [31:0] empty_252_fu_374;
reg   [31:0] empty_253_fu_378;
reg   [31:0] empty_254_fu_382;
reg   [31:0] empty_255_fu_386;
reg   [31:0] empty_256_fu_390;
reg   [31:0] empty_257_fu_394;
reg   [31:0] empty_258_fu_398;
reg   [31:0] empty_259_fu_402;
reg   [31:0] empty_260_fu_406;
reg   [31:0] empty_261_fu_410;
reg   [31:0] empty_262_fu_414;
reg   [31:0] empty_263_fu_418;
reg   [31:0] empty_264_fu_422;
reg   [31:0] empty_265_fu_426;
reg   [31:0] empty_266_fu_430;
reg   [31:0] empty_267_fu_434;
reg   [31:0] empty_268_fu_438;
reg   [31:0] empty_269_fu_442;
reg   [31:0] empty_270_fu_446;
reg   [31:0] empty_271_fu_450;
reg   [31:0] empty_272_fu_454;
reg   [31:0] empty_273_fu_458;
reg   [31:0] empty_274_fu_462;
reg   [31:0] empty_275_fu_466;
reg   [31:0] empty_276_fu_470;
reg   [31:0] empty_277_fu_474;
reg   [31:0] empty_278_fu_478;
reg   [31:0] empty_279_fu_482;
reg   [31:0] empty_280_fu_486;
reg   [31:0] empty_281_fu_490;
reg   [31:0] empty_282_fu_494;
reg   [31:0] empty_283_fu_498;
reg   [31:0] empty_284_fu_502;
reg   [31:0] empty_285_fu_506;
reg   [31:0] empty_286_fu_510;
reg   [31:0] empty_287_fu_514;
reg   [31:0] empty_288_fu_518;
reg   [31:0] empty_289_fu_522;
reg   [31:0] empty_290_fu_526;
reg   [31:0] empty_291_fu_530;
reg   [31:0] empty_292_fu_534;
reg   [31:0] empty_293_fu_538;
reg   [31:0] empty_294_fu_542;
reg   [31:0] empty_295_fu_546;
reg   [31:0] empty_296_fu_550;
reg   [31:0] empty_297_fu_554;
reg   [31:0] empty_298_fu_558;
reg   [31:0] empty_299_fu_562;
reg   [31:0] empty_300_fu_566;
reg   [31:0] empty_301_fu_570;
wire    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1142(
    .din0(D_inv_reload),
    .din1(D_inv_1_reload),
    .din2(D_inv_2_reload),
    .din3(D_inv_3_reload),
    .din4(D_inv_4_reload),
    .din5(D_inv_5_reload),
    .din6(D_inv_6_reload),
    .din7(D_inv_7_reload),
    .din8(trunc_ln162_fu_1506_p1),
    .dout(tmp_8_fu_1510_p10)
);

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1143(
    .din0(mux_case_09029_reload),
    .din1(L_inv_load),
    .din2(L_inv_1_load),
    .din3(L_inv_2_load),
    .din4(L_inv_3_load),
    .din5(L_inv_4_load),
    .din6(L_inv_5_load),
    .din7(L_inv_6_load),
    .din8(trunc_ln162_fu_1506_p1),
    .dout(tmp_9_fu_1540_p10)
);

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1144(
    .din0(mux_case_010632_reload),
    .din1(L_inv_load_1),
    .din2(L_inv_1_load_1),
    .din3(L_inv_2_load_1),
    .din4(L_inv_3_load_1),
    .din5(L_inv_4_load_1),
    .din6(L_inv_5_load_1),
    .din7(L_inv_6_load_1),
    .din8(trunc_ln162_fu_1506_p1),
    .dout(tmp_1_fu_1563_p10)
);

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1145(
    .din0(mux_case_012235_reload),
    .din1(L_inv_load_2),
    .din2(L_inv_1_load_2),
    .din3(L_inv_2_load_2),
    .din4(L_inv_3_load_2),
    .din5(L_inv_4_load_2),
    .din6(L_inv_5_load_2),
    .din7(L_inv_6_load_2),
    .din8(trunc_ln162_fu_1506_p1),
    .dout(tmp_2_fu_1586_p10)
);

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1146(
    .din0(mux_case_013838_reload),
    .din1(L_inv_load_3),
    .din2(L_inv_1_load_3),
    .din3(L_inv_2_load_3),
    .din4(L_inv_3_load_3),
    .din5(L_inv_4_load_3),
    .din6(L_inv_5_load_3),
    .din7(L_inv_6_load_3),
    .din8(trunc_ln162_fu_1506_p1),
    .dout(tmp_3_fu_1609_p10)
);

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1147(
    .din0(mux_case_015441_reload),
    .din1(L_inv_load_4),
    .din2(L_inv_1_load_4),
    .din3(L_inv_2_load_4),
    .din4(L_inv_3_load_4),
    .din5(L_inv_4_load_4),
    .din6(L_inv_5_load_4),
    .din7(L_inv_6_load_4),
    .din8(trunc_ln162_fu_1506_p1),
    .dout(tmp_s_fu_1632_p10)
);

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1148(
    .din0(mux_case_017044_reload),
    .din1(L_inv_load_5),
    .din2(L_inv_1_load_5),
    .din3(L_inv_2_load_5),
    .din4(L_inv_3_load_5),
    .din5(L_inv_4_load_5),
    .din6(L_inv_5_load_5),
    .din7(L_inv_6_load_5),
    .din8(trunc_ln162_fu_1506_p1),
    .dout(tmp_4_fu_1655_p10)
);

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1149(
    .din0(mux_case_018647_reload),
    .din1(L_inv_load_6),
    .din2(L_inv_1_load_6),
    .din3(L_inv_2_load_6),
    .din4(L_inv_3_load_6),
    .din5(L_inv_4_load_6),
    .din6(L_inv_5_load_6),
    .din7(L_inv_6_load_6),
    .din8(trunc_ln162_fu_1506_p1),
    .dout(tmp_5_fu_1678_p10)
);

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1150(
    .din0(mux_case_020250_reload),
    .din1(L_inv_load_7),
    .din2(L_inv_1_load_7),
    .din3(L_inv_2_load_7),
    .din4(L_inv_3_load_7),
    .din5(L_inv_4_load_7),
    .din6(L_inv_5_load_7),
    .din7(L_inv_6_load_7),
    .din8(trunc_ln162_fu_1506_p1),
    .dout(tmp_6_fu_1701_p10)
);

omp_reconstruction_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln162_fu_1494_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_314 <= add_ln162_fu_1500_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_314 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln162_reg_2699 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_239_fu_322 <= grp_fu_3283_p_dout0;
        empty_247_fu_354 <= grp_fu_3287_p_dout0;
        empty_255_fu_386 <= grp_fu_8251_p_dout0;
        empty_263_fu_418 <= grp_fu_8255_p_dout0;
        empty_271_fu_450 <= grp_fu_8259_p_dout0;
        empty_279_fu_482 <= grp_fu_8263_p_dout0;
        empty_287_fu_514 <= grp_fu_8267_p_dout0;
        empty_295_fu_546 <= grp_fu_8271_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln162_reg_2699 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_240_fu_326 <= grp_fu_3283_p_dout0;
        empty_248_fu_358 <= grp_fu_3287_p_dout0;
        empty_256_fu_390 <= grp_fu_8251_p_dout0;
        empty_264_fu_422 <= grp_fu_8255_p_dout0;
        empty_272_fu_454 <= grp_fu_8259_p_dout0;
        empty_280_fu_486 <= grp_fu_8263_p_dout0;
        empty_288_fu_518 <= grp_fu_8267_p_dout0;
        empty_296_fu_550 <= grp_fu_8271_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln162_reg_2699 == 3'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_241_fu_330 <= grp_fu_3283_p_dout0;
        empty_249_fu_362 <= grp_fu_3287_p_dout0;
        empty_257_fu_394 <= grp_fu_8251_p_dout0;
        empty_265_fu_426 <= grp_fu_8255_p_dout0;
        empty_273_fu_458 <= grp_fu_8259_p_dout0;
        empty_281_fu_490 <= grp_fu_8263_p_dout0;
        empty_289_fu_522 <= grp_fu_8267_p_dout0;
        empty_297_fu_554 <= grp_fu_8271_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln162_reg_2699 == 3'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_242_fu_334 <= grp_fu_3283_p_dout0;
        empty_250_fu_366 <= grp_fu_3287_p_dout0;
        empty_258_fu_398 <= grp_fu_8251_p_dout0;
        empty_266_fu_430 <= grp_fu_8255_p_dout0;
        empty_274_fu_462 <= grp_fu_8259_p_dout0;
        empty_282_fu_494 <= grp_fu_8263_p_dout0;
        empty_290_fu_526 <= grp_fu_8267_p_dout0;
        empty_298_fu_558 <= grp_fu_8271_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln162_reg_2699 == 3'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_243_fu_338 <= grp_fu_3283_p_dout0;
        empty_251_fu_370 <= grp_fu_3287_p_dout0;
        empty_259_fu_402 <= grp_fu_8251_p_dout0;
        empty_267_fu_434 <= grp_fu_8255_p_dout0;
        empty_275_fu_466 <= grp_fu_8259_p_dout0;
        empty_283_fu_498 <= grp_fu_8263_p_dout0;
        empty_291_fu_530 <= grp_fu_8267_p_dout0;
        empty_299_fu_562 <= grp_fu_8271_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln162_reg_2699 == 3'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_244_fu_342 <= grp_fu_3283_p_dout0;
        empty_252_fu_374 <= grp_fu_3287_p_dout0;
        empty_260_fu_406 <= grp_fu_8251_p_dout0;
        empty_268_fu_438 <= grp_fu_8255_p_dout0;
        empty_276_fu_470 <= grp_fu_8259_p_dout0;
        empty_284_fu_502 <= grp_fu_8263_p_dout0;
        empty_292_fu_534 <= grp_fu_8267_p_dout0;
        empty_300_fu_566 <= grp_fu_8271_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln162_reg_2699 == 3'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_245_fu_346 <= grp_fu_3283_p_dout0;
        empty_253_fu_378 <= grp_fu_3287_p_dout0;
        empty_261_fu_410 <= grp_fu_8251_p_dout0;
        empty_269_fu_442 <= grp_fu_8255_p_dout0;
        empty_277_fu_474 <= grp_fu_8259_p_dout0;
        empty_285_fu_506 <= grp_fu_8263_p_dout0;
        empty_293_fu_538 <= grp_fu_8267_p_dout0;
        empty_301_fu_570 <= grp_fu_8271_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln162_reg_2699 == 3'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_246_fu_350 <= grp_fu_3287_p_dout0;
        empty_254_fu_382 <= grp_fu_8251_p_dout0;
        empty_262_fu_414 <= grp_fu_8255_p_dout0;
        empty_270_fu_446 <= grp_fu_8259_p_dout0;
        empty_278_fu_478 <= grp_fu_8263_p_dout0;
        empty_286_fu_510 <= grp_fu_8267_p_dout0;
        empty_294_fu_542 <= grp_fu_8271_p_dout0;
        empty_fu_318 <= grp_fu_3283_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln162_reg_2699 <= trunc_ln162_fu_1506_p1;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_10 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_10 = i_fu_314;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out10_ap_vld = 1'b1;
    end else begin
        p_out10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out11_ap_vld = 1'b1;
    end else begin
        p_out11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out12_ap_vld = 1'b1;
    end else begin
        p_out12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out13_ap_vld = 1'b1;
    end else begin
        p_out13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out14_ap_vld = 1'b1;
    end else begin
        p_out14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out15_ap_vld = 1'b1;
    end else begin
        p_out15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out16_ap_vld = 1'b1;
    end else begin
        p_out16_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out17_ap_vld = 1'b1;
    end else begin
        p_out17_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out18_ap_vld = 1'b1;
    end else begin
        p_out18_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out19_ap_vld = 1'b1;
    end else begin
        p_out19_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out20_ap_vld = 1'b1;
    end else begin
        p_out20_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out21_ap_vld = 1'b1;
    end else begin
        p_out21_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out22_ap_vld = 1'b1;
    end else begin
        p_out22_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out23_ap_vld = 1'b1;
    end else begin
        p_out23_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out24_ap_vld = 1'b1;
    end else begin
        p_out24_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out25_ap_vld = 1'b1;
    end else begin
        p_out25_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out26_ap_vld = 1'b1;
    end else begin
        p_out26_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out27_ap_vld = 1'b1;
    end else begin
        p_out27_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out28_ap_vld = 1'b1;
    end else begin
        p_out28_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out29_ap_vld = 1'b1;
    end else begin
        p_out29_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out2_ap_vld = 1'b1;
    end else begin
        p_out2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out30_ap_vld = 1'b1;
    end else begin
        p_out30_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out31_ap_vld = 1'b1;
    end else begin
        p_out31_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out32_ap_vld = 1'b1;
    end else begin
        p_out32_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out33_ap_vld = 1'b1;
    end else begin
        p_out33_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out34_ap_vld = 1'b1;
    end else begin
        p_out34_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out35_ap_vld = 1'b1;
    end else begin
        p_out35_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out36_ap_vld = 1'b1;
    end else begin
        p_out36_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out37_ap_vld = 1'b1;
    end else begin
        p_out37_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out38_ap_vld = 1'b1;
    end else begin
        p_out38_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out39_ap_vld = 1'b1;
    end else begin
        p_out39_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out3_ap_vld = 1'b1;
    end else begin
        p_out3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out40_ap_vld = 1'b1;
    end else begin
        p_out40_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out41_ap_vld = 1'b1;
    end else begin
        p_out41_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out42_ap_vld = 1'b1;
    end else begin
        p_out42_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out43_ap_vld = 1'b1;
    end else begin
        p_out43_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out44_ap_vld = 1'b1;
    end else begin
        p_out44_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out45_ap_vld = 1'b1;
    end else begin
        p_out45_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out46_ap_vld = 1'b1;
    end else begin
        p_out46_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out47_ap_vld = 1'b1;
    end else begin
        p_out47_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out48_ap_vld = 1'b1;
    end else begin
        p_out48_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out49_ap_vld = 1'b1;
    end else begin
        p_out49_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out4_ap_vld = 1'b1;
    end else begin
        p_out4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out50_ap_vld = 1'b1;
    end else begin
        p_out50_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out51_ap_vld = 1'b1;
    end else begin
        p_out51_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out52_ap_vld = 1'b1;
    end else begin
        p_out52_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out53_ap_vld = 1'b1;
    end else begin
        p_out53_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out54_ap_vld = 1'b1;
    end else begin
        p_out54_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out55_ap_vld = 1'b1;
    end else begin
        p_out55_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out56_ap_vld = 1'b1;
    end else begin
        p_out56_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out57_ap_vld = 1'b1;
    end else begin
        p_out57_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out58_ap_vld = 1'b1;
    end else begin
        p_out58_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out59_ap_vld = 1'b1;
    end else begin
        p_out59_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out5_ap_vld = 1'b1;
    end else begin
        p_out5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out60_ap_vld = 1'b1;
    end else begin
        p_out60_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out61_ap_vld = 1'b1;
    end else begin
        p_out61_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out62_ap_vld = 1'b1;
    end else begin
        p_out62_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out63_ap_vld = 1'b1;
    end else begin
        p_out63_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out6_ap_vld = 1'b1;
    end else begin
        p_out6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out7_ap_vld = 1'b1;
    end else begin
        p_out7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out8_ap_vld = 1'b1;
    end else begin
        p_out8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out9_ap_vld = 1'b1;
    end else begin
        p_out9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_1494_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln162_fu_1500_p2 = (ap_sig_allocacmp_i_10 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_3283_p_ce = 1'b1;

assign grp_fu_3283_p_din0 = tmp_8_fu_1510_p10;

assign grp_fu_3283_p_din1 = tmp_9_fu_1540_p10;

assign grp_fu_3287_p_ce = 1'b1;

assign grp_fu_3287_p_din0 = tmp_8_fu_1510_p10;

assign grp_fu_3287_p_din1 = tmp_1_fu_1563_p10;

assign grp_fu_8251_p_ce = 1'b1;

assign grp_fu_8251_p_din0 = tmp_8_fu_1510_p10;

assign grp_fu_8251_p_din1 = tmp_2_fu_1586_p10;

assign grp_fu_8255_p_ce = 1'b1;

assign grp_fu_8255_p_din0 = tmp_8_fu_1510_p10;

assign grp_fu_8255_p_din1 = tmp_3_fu_1609_p10;

assign grp_fu_8259_p_ce = 1'b1;

assign grp_fu_8259_p_din0 = tmp_8_fu_1510_p10;

assign grp_fu_8259_p_din1 = tmp_s_fu_1632_p10;

assign grp_fu_8263_p_ce = 1'b1;

assign grp_fu_8263_p_din0 = tmp_8_fu_1510_p10;

assign grp_fu_8263_p_din1 = tmp_4_fu_1655_p10;

assign grp_fu_8267_p_ce = 1'b1;

assign grp_fu_8267_p_din0 = tmp_8_fu_1510_p10;

assign grp_fu_8267_p_din1 = tmp_5_fu_1678_p10;

assign grp_fu_8271_p_ce = 1'b1;

assign grp_fu_8271_p_din0 = tmp_8_fu_1510_p10;

assign grp_fu_8271_p_din1 = tmp_6_fu_1701_p10;

assign icmp_ln162_fu_1494_p2 = ((ap_sig_allocacmp_i_10 == 4'd8) ? 1'b1 : 1'b0);

assign p_out = empty_301_fu_570;

assign p_out1 = empty_300_fu_566;

assign p_out10 = empty_291_fu_530;

assign p_out11 = empty_290_fu_526;

assign p_out12 = empty_289_fu_522;

assign p_out13 = empty_288_fu_518;

assign p_out14 = empty_287_fu_514;

assign p_out15 = empty_286_fu_510;

assign p_out16 = empty_285_fu_506;

assign p_out17 = empty_284_fu_502;

assign p_out18 = empty_283_fu_498;

assign p_out19 = empty_282_fu_494;

assign p_out2 = empty_299_fu_562;

assign p_out20 = empty_281_fu_490;

assign p_out21 = empty_280_fu_486;

assign p_out22 = empty_279_fu_482;

assign p_out23 = empty_278_fu_478;

assign p_out24 = empty_277_fu_474;

assign p_out25 = empty_276_fu_470;

assign p_out26 = empty_275_fu_466;

assign p_out27 = empty_274_fu_462;

assign p_out28 = empty_273_fu_458;

assign p_out29 = empty_272_fu_454;

assign p_out3 = empty_298_fu_558;

assign p_out30 = empty_271_fu_450;

assign p_out31 = empty_270_fu_446;

assign p_out32 = empty_269_fu_442;

assign p_out33 = empty_268_fu_438;

assign p_out34 = empty_267_fu_434;

assign p_out35 = empty_266_fu_430;

assign p_out36 = empty_265_fu_426;

assign p_out37 = empty_264_fu_422;

assign p_out38 = empty_263_fu_418;

assign p_out39 = empty_262_fu_414;

assign p_out4 = empty_297_fu_554;

assign p_out40 = empty_261_fu_410;

assign p_out41 = empty_260_fu_406;

assign p_out42 = empty_259_fu_402;

assign p_out43 = empty_258_fu_398;

assign p_out44 = empty_257_fu_394;

assign p_out45 = empty_256_fu_390;

assign p_out46 = empty_255_fu_386;

assign p_out47 = empty_254_fu_382;

assign p_out48 = empty_253_fu_378;

assign p_out49 = empty_252_fu_374;

assign p_out5 = empty_296_fu_550;

assign p_out50 = empty_251_fu_370;

assign p_out51 = empty_250_fu_366;

assign p_out52 = empty_249_fu_362;

assign p_out53 = empty_248_fu_358;

assign p_out54 = empty_247_fu_354;

assign p_out55 = empty_246_fu_350;

assign p_out56 = empty_245_fu_346;

assign p_out57 = empty_244_fu_342;

assign p_out58 = empty_243_fu_338;

assign p_out59 = empty_242_fu_334;

assign p_out6 = empty_295_fu_546;

assign p_out60 = empty_241_fu_330;

assign p_out61 = empty_240_fu_326;

assign p_out62 = empty_239_fu_322;

assign p_out63 = empty_fu_318;

assign p_out7 = empty_294_fu_542;

assign p_out8 = empty_293_fu_538;

assign p_out9 = empty_292_fu_534;

assign trunc_ln162_fu_1506_p1 = ap_sig_allocacmp_i_10[2:0];

endmodule //omp_reconstruction_acd_inversion_Pipeline_calc_T
