// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module omp_reconstruction_omp_reconstruction_Pipeline_mult_theta (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        G_inv_load,
        G_inv_8_load,
        G_inv_16_load,
        G_inv_24_load,
        G_inv_32_load,
        G_inv_40_load,
        G_inv_48_load,
        G_inv_56_load,
        b_reload,
        G_inv_1_load,
        G_inv_9_load,
        G_inv_17_load,
        G_inv_25_load,
        G_inv_33_load,
        G_inv_41_load,
        G_inv_49_load,
        G_inv_57_load,
        b_1_reload,
        G_inv_2_load,
        G_inv_10_load,
        G_inv_18_load,
        G_inv_26_load,
        G_inv_34_load,
        G_inv_42_load,
        G_inv_50_load,
        G_inv_58_load,
        b_2_reload,
        G_inv_3_load,
        G_inv_11_load,
        G_inv_19_load,
        G_inv_27_load,
        G_inv_35_load,
        G_inv_43_load,
        G_inv_51_load,
        G_inv_59_load,
        b_3_reload,
        G_inv_4_load,
        G_inv_12_load,
        G_inv_20_load,
        G_inv_28_load,
        G_inv_36_load,
        G_inv_44_load,
        G_inv_52_load,
        G_inv_60_load,
        b_4_reload,
        G_inv_5_load,
        G_inv_13_load,
        G_inv_21_load,
        G_inv_29_load,
        G_inv_37_load,
        G_inv_45_load,
        G_inv_53_load,
        G_inv_61_load,
        b_5_reload,
        G_inv_6_load,
        G_inv_14_load,
        G_inv_22_load,
        G_inv_30_load,
        G_inv_38_load,
        G_inv_46_load,
        G_inv_54_load,
        G_inv_62_load,
        b_6_reload,
        G_inv_7_load,
        G_inv_15_load,
        G_inv_23_load,
        G_inv_31_load,
        G_inv_39_load,
        G_inv_47_load,
        G_inv_55_load,
        G_inv_63_load,
        b_7_reload,
        theta_address0,
        theta_ce0,
        theta_we0,
        theta_d0,
        grp_fu_4359_p_din0,
        grp_fu_4359_p_din1,
        grp_fu_4359_p_opcode,
        grp_fu_4359_p_dout0,
        grp_fu_4359_p_ce,
        grp_fu_4363_p_din0,
        grp_fu_4363_p_din1,
        grp_fu_4363_p_opcode,
        grp_fu_4363_p_dout0,
        grp_fu_4363_p_ce,
        grp_fu_4367_p_din0,
        grp_fu_4367_p_din1,
        grp_fu_4367_p_opcode,
        grp_fu_4367_p_dout0,
        grp_fu_4367_p_ce,
        grp_fu_4371_p_din0,
        grp_fu_4371_p_din1,
        grp_fu_4371_p_opcode,
        grp_fu_4371_p_dout0,
        grp_fu_4371_p_ce,
        grp_fu_4375_p_din0,
        grp_fu_4375_p_din1,
        grp_fu_4375_p_opcode,
        grp_fu_4375_p_dout0,
        grp_fu_4375_p_ce,
        grp_fu_4379_p_din0,
        grp_fu_4379_p_din1,
        grp_fu_4379_p_opcode,
        grp_fu_4379_p_dout0,
        grp_fu_4379_p_ce,
        grp_fu_4383_p_din0,
        grp_fu_4383_p_din1,
        grp_fu_4383_p_opcode,
        grp_fu_4383_p_dout0,
        grp_fu_4383_p_ce,
        grp_fu_4387_p_din0,
        grp_fu_4387_p_din1,
        grp_fu_4387_p_opcode,
        grp_fu_4387_p_dout0,
        grp_fu_4387_p_ce,
        grp_fu_4551_p_din0,
        grp_fu_4551_p_din1,
        grp_fu_4551_p_dout0,
        grp_fu_4551_p_ce,
        grp_fu_4555_p_din0,
        grp_fu_4555_p_din1,
        grp_fu_4555_p_dout0,
        grp_fu_4555_p_ce,
        grp_fu_4559_p_din0,
        grp_fu_4559_p_din1,
        grp_fu_4559_p_dout0,
        grp_fu_4559_p_ce,
        grp_fu_4563_p_din0,
        grp_fu_4563_p_din1,
        grp_fu_4563_p_dout0,
        grp_fu_4563_p_ce,
        grp_fu_4567_p_din0,
        grp_fu_4567_p_din1,
        grp_fu_4567_p_dout0,
        grp_fu_4567_p_ce,
        grp_fu_4571_p_din0,
        grp_fu_4571_p_din1,
        grp_fu_4571_p_dout0,
        grp_fu_4571_p_ce,
        grp_fu_4575_p_din0,
        grp_fu_4575_p_din1,
        grp_fu_4575_p_dout0,
        grp_fu_4575_p_ce,
        grp_fu_4579_p_din0,
        grp_fu_4579_p_din1,
        grp_fu_4579_p_dout0,
        grp_fu_4579_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] G_inv_load;
input  [31:0] G_inv_8_load;
input  [31:0] G_inv_16_load;
input  [31:0] G_inv_24_load;
input  [31:0] G_inv_32_load;
input  [31:0] G_inv_40_load;
input  [31:0] G_inv_48_load;
input  [31:0] G_inv_56_load;
input  [31:0] b_reload;
input  [31:0] G_inv_1_load;
input  [31:0] G_inv_9_load;
input  [31:0] G_inv_17_load;
input  [31:0] G_inv_25_load;
input  [31:0] G_inv_33_load;
input  [31:0] G_inv_41_load;
input  [31:0] G_inv_49_load;
input  [31:0] G_inv_57_load;
input  [31:0] b_1_reload;
input  [31:0] G_inv_2_load;
input  [31:0] G_inv_10_load;
input  [31:0] G_inv_18_load;
input  [31:0] G_inv_26_load;
input  [31:0] G_inv_34_load;
input  [31:0] G_inv_42_load;
input  [31:0] G_inv_50_load;
input  [31:0] G_inv_58_load;
input  [31:0] b_2_reload;
input  [31:0] G_inv_3_load;
input  [31:0] G_inv_11_load;
input  [31:0] G_inv_19_load;
input  [31:0] G_inv_27_load;
input  [31:0] G_inv_35_load;
input  [31:0] G_inv_43_load;
input  [31:0] G_inv_51_load;
input  [31:0] G_inv_59_load;
input  [31:0] b_3_reload;
input  [31:0] G_inv_4_load;
input  [31:0] G_inv_12_load;
input  [31:0] G_inv_20_load;
input  [31:0] G_inv_28_load;
input  [31:0] G_inv_36_load;
input  [31:0] G_inv_44_load;
input  [31:0] G_inv_52_load;
input  [31:0] G_inv_60_load;
input  [31:0] b_4_reload;
input  [31:0] G_inv_5_load;
input  [31:0] G_inv_13_load;
input  [31:0] G_inv_21_load;
input  [31:0] G_inv_29_load;
input  [31:0] G_inv_37_load;
input  [31:0] G_inv_45_load;
input  [31:0] G_inv_53_load;
input  [31:0] G_inv_61_load;
input  [31:0] b_5_reload;
input  [31:0] G_inv_6_load;
input  [31:0] G_inv_14_load;
input  [31:0] G_inv_22_load;
input  [31:0] G_inv_30_load;
input  [31:0] G_inv_38_load;
input  [31:0] G_inv_46_load;
input  [31:0] G_inv_54_load;
input  [31:0] G_inv_62_load;
input  [31:0] b_6_reload;
input  [31:0] G_inv_7_load;
input  [31:0] G_inv_15_load;
input  [31:0] G_inv_23_load;
input  [31:0] G_inv_31_load;
input  [31:0] G_inv_39_load;
input  [31:0] G_inv_47_load;
input  [31:0] G_inv_55_load;
input  [31:0] G_inv_63_load;
input  [31:0] b_7_reload;
output  [2:0] theta_address0;
output   theta_ce0;
output   theta_we0;
output  [31:0] theta_d0;
output  [31:0] grp_fu_4359_p_din0;
output  [31:0] grp_fu_4359_p_din1;
output  [0:0] grp_fu_4359_p_opcode;
input  [31:0] grp_fu_4359_p_dout0;
output   grp_fu_4359_p_ce;
output  [31:0] grp_fu_4363_p_din0;
output  [31:0] grp_fu_4363_p_din1;
output  [0:0] grp_fu_4363_p_opcode;
input  [31:0] grp_fu_4363_p_dout0;
output   grp_fu_4363_p_ce;
output  [31:0] grp_fu_4367_p_din0;
output  [31:0] grp_fu_4367_p_din1;
output  [0:0] grp_fu_4367_p_opcode;
input  [31:0] grp_fu_4367_p_dout0;
output   grp_fu_4367_p_ce;
output  [31:0] grp_fu_4371_p_din0;
output  [31:0] grp_fu_4371_p_din1;
output  [0:0] grp_fu_4371_p_opcode;
input  [31:0] grp_fu_4371_p_dout0;
output   grp_fu_4371_p_ce;
output  [31:0] grp_fu_4375_p_din0;
output  [31:0] grp_fu_4375_p_din1;
output  [0:0] grp_fu_4375_p_opcode;
input  [31:0] grp_fu_4375_p_dout0;
output   grp_fu_4375_p_ce;
output  [31:0] grp_fu_4379_p_din0;
output  [31:0] grp_fu_4379_p_din1;
output  [0:0] grp_fu_4379_p_opcode;
input  [31:0] grp_fu_4379_p_dout0;
output   grp_fu_4379_p_ce;
output  [31:0] grp_fu_4383_p_din0;
output  [31:0] grp_fu_4383_p_din1;
output  [0:0] grp_fu_4383_p_opcode;
input  [31:0] grp_fu_4383_p_dout0;
output   grp_fu_4383_p_ce;
output  [31:0] grp_fu_4387_p_din0;
output  [31:0] grp_fu_4387_p_din1;
output  [0:0] grp_fu_4387_p_opcode;
input  [31:0] grp_fu_4387_p_dout0;
output   grp_fu_4387_p_ce;
output  [31:0] grp_fu_4551_p_din0;
output  [31:0] grp_fu_4551_p_din1;
input  [31:0] grp_fu_4551_p_dout0;
output   grp_fu_4551_p_ce;
output  [31:0] grp_fu_4555_p_din0;
output  [31:0] grp_fu_4555_p_din1;
input  [31:0] grp_fu_4555_p_dout0;
output   grp_fu_4555_p_ce;
output  [31:0] grp_fu_4559_p_din0;
output  [31:0] grp_fu_4559_p_din1;
input  [31:0] grp_fu_4559_p_dout0;
output   grp_fu_4559_p_ce;
output  [31:0] grp_fu_4563_p_din0;
output  [31:0] grp_fu_4563_p_din1;
input  [31:0] grp_fu_4563_p_dout0;
output   grp_fu_4563_p_ce;
output  [31:0] grp_fu_4567_p_din0;
output  [31:0] grp_fu_4567_p_din1;
input  [31:0] grp_fu_4567_p_dout0;
output   grp_fu_4567_p_ce;
output  [31:0] grp_fu_4571_p_din0;
output  [31:0] grp_fu_4571_p_din1;
input  [31:0] grp_fu_4571_p_dout0;
output   grp_fu_4571_p_ce;
output  [31:0] grp_fu_4575_p_din0;
output  [31:0] grp_fu_4575_p_din1;
input  [31:0] grp_fu_4575_p_dout0;
output   grp_fu_4575_p_ce;
output  [31:0] grp_fu_4579_p_din0;
output  [31:0] grp_fu_4579_p_din1;
input  [31:0] grp_fu_4579_p_dout0;
output   grp_fu_4579_p_ce;

reg ap_idle;
reg theta_ce0;
reg theta_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln294_fu_700_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] i_1_reg_1173;
reg   [3:0] i_1_reg_1173_pp0_iter1_reg;
reg   [3:0] i_1_reg_1173_pp0_iter2_reg;
reg   [3:0] i_1_reg_1173_pp0_iter3_reg;
reg   [3:0] i_1_reg_1173_pp0_iter4_reg;
reg   [3:0] i_1_reg_1173_pp0_iter5_reg;
reg   [3:0] i_1_reg_1173_pp0_iter6_reg;
reg   [3:0] i_1_reg_1173_pp0_iter7_reg;
reg   [3:0] i_1_reg_1173_pp0_iter8_reg;
reg   [3:0] i_1_reg_1173_pp0_iter9_reg;
reg   [3:0] i_1_reg_1173_pp0_iter10_reg;
reg   [3:0] i_1_reg_1173_pp0_iter11_reg;
reg   [3:0] i_1_reg_1173_pp0_iter12_reg;
reg   [3:0] i_1_reg_1173_pp0_iter13_reg;
reg   [3:0] i_1_reg_1173_pp0_iter14_reg;
reg   [3:0] i_1_reg_1173_pp0_iter15_reg;
reg   [3:0] i_1_reg_1173_pp0_iter16_reg;
wire   [2:0] trunc_ln296_fu_712_p1;
reg   [2:0] trunc_ln296_reg_1182;
reg   [2:0] trunc_ln296_reg_1182_pp0_iter1_reg;
reg   [2:0] trunc_ln296_reg_1182_pp0_iter2_reg;
reg   [2:0] trunc_ln296_reg_1182_pp0_iter3_reg;
reg   [2:0] trunc_ln296_reg_1182_pp0_iter4_reg;
reg   [2:0] trunc_ln296_reg_1182_pp0_iter5_reg;
reg   [2:0] trunc_ln296_reg_1182_pp0_iter6_reg;
reg   [2:0] trunc_ln296_reg_1182_pp0_iter7_reg;
reg   [2:0] trunc_ln296_reg_1182_pp0_iter8_reg;
reg   [2:0] trunc_ln296_reg_1182_pp0_iter9_reg;
reg   [2:0] trunc_ln296_reg_1182_pp0_iter10_reg;
reg   [2:0] trunc_ln296_reg_1182_pp0_iter11_reg;
reg   [2:0] trunc_ln296_reg_1182_pp0_iter12_reg;
reg   [2:0] trunc_ln296_reg_1182_pp0_iter13_reg;
wire   [31:0] tmp_5_fu_716_p10;
reg   [31:0] mul1_reg_1198;
wire   [31:0] tmp_6_fu_744_p10;
reg   [31:0] sum_reg_1208;
reg   [31:0] mul198_1_reg_1213;
wire   [31:0] tmp_7_fu_758_p10;
reg   [31:0] sum_1_reg_1223;
reg   [31:0] mul198_2_reg_1228;
wire   [31:0] tmp_8_fu_772_p10;
reg   [31:0] sum_2_reg_1238;
reg   [31:0] mul198_3_reg_1243;
wire   [31:0] tmp_9_fu_786_p10;
reg   [31:0] sum_3_reg_1253;
reg   [31:0] mul198_4_reg_1258;
wire   [31:0] tmp_s_fu_800_p10;
reg   [31:0] sum_4_reg_1268;
reg   [31:0] mul198_5_reg_1273;
wire   [31:0] tmp_1_fu_814_p10;
reg   [31:0] sum_5_reg_1283;
reg   [31:0] mul198_6_reg_1288;
wire   [31:0] tmp_3_fu_828_p10;
reg   [31:0] sum_6_reg_1298;
reg   [31:0] mul198_7_reg_1303;
wire   [63:0] zext_ln294_fu_842_p1;
wire    ap_block_pp0_stage0;
reg   [3:0] i_fu_176;
wire   [3:0] add_ln294_fu_706_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_1;
wire   [2:0] tmp_5_fu_716_p9;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_done_reg = 1'b0;
end

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1753(
    .din0(G_inv_load),
    .din1(G_inv_8_load),
    .din2(G_inv_16_load),
    .din3(G_inv_24_load),
    .din4(G_inv_32_load),
    .din5(G_inv_40_load),
    .din6(G_inv_48_load),
    .din7(G_inv_56_load),
    .din8(tmp_5_fu_716_p9),
    .dout(tmp_5_fu_716_p10)
);

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1754(
    .din0(G_inv_1_load),
    .din1(G_inv_9_load),
    .din2(G_inv_17_load),
    .din3(G_inv_25_load),
    .din4(G_inv_33_load),
    .din5(G_inv_41_load),
    .din6(G_inv_49_load),
    .din7(G_inv_57_load),
    .din8(trunc_ln296_reg_1182_pp0_iter1_reg),
    .dout(tmp_6_fu_744_p10)
);

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1755(
    .din0(G_inv_2_load),
    .din1(G_inv_10_load),
    .din2(G_inv_18_load),
    .din3(G_inv_26_load),
    .din4(G_inv_34_load),
    .din5(G_inv_42_load),
    .din6(G_inv_50_load),
    .din7(G_inv_58_load),
    .din8(trunc_ln296_reg_1182_pp0_iter3_reg),
    .dout(tmp_7_fu_758_p10)
);

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1756(
    .din0(G_inv_3_load),
    .din1(G_inv_11_load),
    .din2(G_inv_19_load),
    .din3(G_inv_27_load),
    .din4(G_inv_35_load),
    .din5(G_inv_43_load),
    .din6(G_inv_51_load),
    .din7(G_inv_59_load),
    .din8(trunc_ln296_reg_1182_pp0_iter5_reg),
    .dout(tmp_8_fu_772_p10)
);

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1757(
    .din0(G_inv_4_load),
    .din1(G_inv_12_load),
    .din2(G_inv_20_load),
    .din3(G_inv_28_load),
    .din4(G_inv_36_load),
    .din5(G_inv_44_load),
    .din6(G_inv_52_load),
    .din7(G_inv_60_load),
    .din8(trunc_ln296_reg_1182_pp0_iter7_reg),
    .dout(tmp_9_fu_786_p10)
);

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1758(
    .din0(G_inv_5_load),
    .din1(G_inv_13_load),
    .din2(G_inv_21_load),
    .din3(G_inv_29_load),
    .din4(G_inv_37_load),
    .din5(G_inv_45_load),
    .din6(G_inv_53_load),
    .din7(G_inv_61_load),
    .din8(trunc_ln296_reg_1182_pp0_iter9_reg),
    .dout(tmp_s_fu_800_p10)
);

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1759(
    .din0(G_inv_6_load),
    .din1(G_inv_14_load),
    .din2(G_inv_22_load),
    .din3(G_inv_30_load),
    .din4(G_inv_38_load),
    .din5(G_inv_46_load),
    .din6(G_inv_54_load),
    .din7(G_inv_62_load),
    .din8(trunc_ln296_reg_1182_pp0_iter11_reg),
    .dout(tmp_1_fu_814_p10)
);

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1760(
    .din0(G_inv_7_load),
    .din1(G_inv_15_load),
    .din2(G_inv_23_load),
    .din3(G_inv_31_load),
    .din4(G_inv_39_load),
    .din5(G_inv_47_load),
    .din6(G_inv_55_load),
    .din7(G_inv_63_load),
    .din8(trunc_ln296_reg_1182_pp0_iter13_reg),
    .dout(tmp_3_fu_828_p10)
);

omp_reconstruction_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter16_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln294_fu_700_p2 == 1'd0))) begin
            i_fu_176 <= add_ln294_fu_706_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_176 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        i_1_reg_1173_pp0_iter10_reg <= i_1_reg_1173_pp0_iter9_reg;
        i_1_reg_1173_pp0_iter11_reg <= i_1_reg_1173_pp0_iter10_reg;
        i_1_reg_1173_pp0_iter12_reg <= i_1_reg_1173_pp0_iter11_reg;
        i_1_reg_1173_pp0_iter13_reg <= i_1_reg_1173_pp0_iter12_reg;
        i_1_reg_1173_pp0_iter14_reg <= i_1_reg_1173_pp0_iter13_reg;
        i_1_reg_1173_pp0_iter15_reg <= i_1_reg_1173_pp0_iter14_reg;
        i_1_reg_1173_pp0_iter16_reg <= i_1_reg_1173_pp0_iter15_reg;
        i_1_reg_1173_pp0_iter2_reg <= i_1_reg_1173_pp0_iter1_reg;
        i_1_reg_1173_pp0_iter3_reg <= i_1_reg_1173_pp0_iter2_reg;
        i_1_reg_1173_pp0_iter4_reg <= i_1_reg_1173_pp0_iter3_reg;
        i_1_reg_1173_pp0_iter5_reg <= i_1_reg_1173_pp0_iter4_reg;
        i_1_reg_1173_pp0_iter6_reg <= i_1_reg_1173_pp0_iter5_reg;
        i_1_reg_1173_pp0_iter7_reg <= i_1_reg_1173_pp0_iter6_reg;
        i_1_reg_1173_pp0_iter8_reg <= i_1_reg_1173_pp0_iter7_reg;
        i_1_reg_1173_pp0_iter9_reg <= i_1_reg_1173_pp0_iter8_reg;
        mul198_1_reg_1213 <= grp_fu_4555_p_dout0;
        mul198_2_reg_1228 <= grp_fu_4559_p_dout0;
        mul198_3_reg_1243 <= grp_fu_4563_p_dout0;
        mul198_4_reg_1258 <= grp_fu_4567_p_dout0;
        mul198_5_reg_1273 <= grp_fu_4571_p_dout0;
        mul198_6_reg_1288 <= grp_fu_4575_p_dout0;
        mul198_7_reg_1303 <= grp_fu_4579_p_dout0;
        sum_1_reg_1223 <= grp_fu_4363_p_dout0;
        sum_2_reg_1238 <= grp_fu_4367_p_dout0;
        sum_3_reg_1253 <= grp_fu_4371_p_dout0;
        sum_4_reg_1268 <= grp_fu_4375_p_dout0;
        sum_5_reg_1283 <= grp_fu_4379_p_dout0;
        sum_6_reg_1298 <= grp_fu_4383_p_dout0;
        sum_reg_1208 <= grp_fu_4359_p_dout0;
        trunc_ln296_reg_1182_pp0_iter10_reg <= trunc_ln296_reg_1182_pp0_iter9_reg;
        trunc_ln296_reg_1182_pp0_iter11_reg <= trunc_ln296_reg_1182_pp0_iter10_reg;
        trunc_ln296_reg_1182_pp0_iter12_reg <= trunc_ln296_reg_1182_pp0_iter11_reg;
        trunc_ln296_reg_1182_pp0_iter13_reg <= trunc_ln296_reg_1182_pp0_iter12_reg;
        trunc_ln296_reg_1182_pp0_iter2_reg <= trunc_ln296_reg_1182_pp0_iter1_reg;
        trunc_ln296_reg_1182_pp0_iter3_reg <= trunc_ln296_reg_1182_pp0_iter2_reg;
        trunc_ln296_reg_1182_pp0_iter4_reg <= trunc_ln296_reg_1182_pp0_iter3_reg;
        trunc_ln296_reg_1182_pp0_iter5_reg <= trunc_ln296_reg_1182_pp0_iter4_reg;
        trunc_ln296_reg_1182_pp0_iter6_reg <= trunc_ln296_reg_1182_pp0_iter5_reg;
        trunc_ln296_reg_1182_pp0_iter7_reg <= trunc_ln296_reg_1182_pp0_iter6_reg;
        trunc_ln296_reg_1182_pp0_iter8_reg <= trunc_ln296_reg_1182_pp0_iter7_reg;
        trunc_ln296_reg_1182_pp0_iter9_reg <= trunc_ln296_reg_1182_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i_1_reg_1173 <= ap_sig_allocacmp_i_1;
        i_1_reg_1173_pp0_iter1_reg <= i_1_reg_1173;
        mul1_reg_1198 <= grp_fu_4551_p_dout0;
        trunc_ln296_reg_1182_pp0_iter1_reg <= trunc_ln296_reg_1182;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln294_fu_700_p2 == 1'd0))) begin
        trunc_ln296_reg_1182 <= trunc_ln296_fu_712_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln294_fu_700_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter16_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_176;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter17 == 1'b1))) begin
        theta_ce0 = 1'b1;
    end else begin
        theta_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter17 == 1'b1))) begin
        theta_we0 = 1'b1;
    end else begin
        theta_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln294_fu_706_p2 = (ap_sig_allocacmp_i_1 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_4359_p_ce = 1'b1;

assign grp_fu_4359_p_din0 = mul1_reg_1198;

assign grp_fu_4359_p_din1 = 32'd0;

assign grp_fu_4359_p_opcode = 2'd0;

assign grp_fu_4363_p_ce = 1'b1;

assign grp_fu_4363_p_din0 = sum_reg_1208;

assign grp_fu_4363_p_din1 = mul198_1_reg_1213;

assign grp_fu_4363_p_opcode = 2'd0;

assign grp_fu_4367_p_ce = 1'b1;

assign grp_fu_4367_p_din0 = sum_1_reg_1223;

assign grp_fu_4367_p_din1 = mul198_2_reg_1228;

assign grp_fu_4367_p_opcode = 2'd0;

assign grp_fu_4371_p_ce = 1'b1;

assign grp_fu_4371_p_din0 = sum_2_reg_1238;

assign grp_fu_4371_p_din1 = mul198_3_reg_1243;

assign grp_fu_4371_p_opcode = 2'd0;

assign grp_fu_4375_p_ce = 1'b1;

assign grp_fu_4375_p_din0 = sum_3_reg_1253;

assign grp_fu_4375_p_din1 = mul198_4_reg_1258;

assign grp_fu_4375_p_opcode = 2'd0;

assign grp_fu_4379_p_ce = 1'b1;

assign grp_fu_4379_p_din0 = sum_4_reg_1268;

assign grp_fu_4379_p_din1 = mul198_5_reg_1273;

assign grp_fu_4379_p_opcode = 2'd0;

assign grp_fu_4383_p_ce = 1'b1;

assign grp_fu_4383_p_din0 = sum_5_reg_1283;

assign grp_fu_4383_p_din1 = mul198_6_reg_1288;

assign grp_fu_4383_p_opcode = 2'd0;

assign grp_fu_4387_p_ce = 1'b1;

assign grp_fu_4387_p_din0 = sum_6_reg_1298;

assign grp_fu_4387_p_din1 = mul198_7_reg_1303;

assign grp_fu_4387_p_opcode = 2'd0;

assign grp_fu_4551_p_ce = 1'b1;

assign grp_fu_4551_p_din0 = tmp_5_fu_716_p10;

assign grp_fu_4551_p_din1 = b_reload;

assign grp_fu_4555_p_ce = 1'b1;

assign grp_fu_4555_p_din0 = tmp_6_fu_744_p10;

assign grp_fu_4555_p_din1 = b_1_reload;

assign grp_fu_4559_p_ce = 1'b1;

assign grp_fu_4559_p_din0 = tmp_7_fu_758_p10;

assign grp_fu_4559_p_din1 = b_2_reload;

assign grp_fu_4563_p_ce = 1'b1;

assign grp_fu_4563_p_din0 = tmp_8_fu_772_p10;

assign grp_fu_4563_p_din1 = b_3_reload;

assign grp_fu_4567_p_ce = 1'b1;

assign grp_fu_4567_p_din0 = tmp_9_fu_786_p10;

assign grp_fu_4567_p_din1 = b_4_reload;

assign grp_fu_4571_p_ce = 1'b1;

assign grp_fu_4571_p_din0 = tmp_s_fu_800_p10;

assign grp_fu_4571_p_din1 = b_5_reload;

assign grp_fu_4575_p_ce = 1'b1;

assign grp_fu_4575_p_din0 = tmp_1_fu_814_p10;

assign grp_fu_4575_p_din1 = b_6_reload;

assign grp_fu_4579_p_ce = 1'b1;

assign grp_fu_4579_p_din0 = tmp_3_fu_828_p10;

assign grp_fu_4579_p_din1 = b_7_reload;

assign icmp_ln294_fu_700_p2 = ((ap_sig_allocacmp_i_1 == 4'd8) ? 1'b1 : 1'b0);

assign theta_address0 = zext_ln294_fu_842_p1;

assign theta_d0 = grp_fu_4387_p_dout0;

assign tmp_5_fu_716_p9 = ap_sig_allocacmp_i_1[2:0];

assign trunc_ln296_fu_712_p1 = ap_sig_allocacmp_i_1[2:0];

assign zext_ln294_fu_842_p1 = i_1_reg_1173_pp0_iter16_reg;

endmodule //omp_reconstruction_omp_reconstruction_Pipeline_mult_theta
