// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module omp_reconstruction_acd_inversion_Pipeline_inv_d_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        D,
        D_1,
        D_2,
        D_3,
        D_4,
        D_5,
        D_6,
        D_7,
        D_inv_7_out,
        D_inv_7_out_ap_vld,
        D_inv_6_out,
        D_inv_6_out_ap_vld,
        D_inv_5_out,
        D_inv_5_out_ap_vld,
        D_inv_4_out,
        D_inv_4_out_ap_vld,
        D_inv_3_out,
        D_inv_3_out_ap_vld,
        D_inv_2_out,
        D_inv_2_out_ap_vld,
        D_inv_1_out,
        D_inv_1_out_ap_vld,
        D_inv_out,
        D_inv_out_ap_vld,
        grp_fu_3300_p_din0,
        grp_fu_3300_p_din1,
        grp_fu_3300_p_dout0,
        grp_fu_3300_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] D;
input  [31:0] D_1;
input  [31:0] D_2;
input  [31:0] D_3;
input  [31:0] D_4;
input  [31:0] D_5;
input  [31:0] D_6;
input  [31:0] D_7;
output  [31:0] D_inv_7_out;
output   D_inv_7_out_ap_vld;
output  [31:0] D_inv_6_out;
output   D_inv_6_out_ap_vld;
output  [31:0] D_inv_5_out;
output   D_inv_5_out_ap_vld;
output  [31:0] D_inv_4_out;
output   D_inv_4_out_ap_vld;
output  [31:0] D_inv_3_out;
output   D_inv_3_out_ap_vld;
output  [31:0] D_inv_2_out;
output   D_inv_2_out_ap_vld;
output  [31:0] D_inv_1_out;
output   D_inv_1_out_ap_vld;
output  [31:0] D_inv_out;
output   D_inv_out_ap_vld;
output  [31:0] grp_fu_3300_p_din0;
output  [31:0] grp_fu_3300_p_din1;
input  [31:0] grp_fu_3300_p_dout0;
output   grp_fu_3300_p_ce;

reg ap_idle;
reg D_inv_7_out_ap_vld;
reg D_inv_6_out_ap_vld;
reg D_inv_5_out_ap_vld;
reg D_inv_4_out_ap_vld;
reg D_inv_3_out_ap_vld;
reg D_inv_2_out_ap_vld;
reg D_inv_1_out_ap_vld;
reg D_inv_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln143_fu_229_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln143_reg_400;
reg   [0:0] icmp_ln143_reg_400_pp0_iter1_reg;
reg   [0:0] icmp_ln143_reg_400_pp0_iter2_reg;
reg   [0:0] icmp_ln143_reg_400_pp0_iter3_reg;
wire   [2:0] trunc_ln143_fu_241_p1;
reg   [2:0] trunc_ln143_reg_404;
reg   [2:0] trunc_ln143_reg_404_pp0_iter1_reg;
reg   [2:0] trunc_ln143_reg_404_pp0_iter2_reg;
reg   [2:0] trunc_ln143_reg_404_pp0_iter3_reg;
reg   [2:0] trunc_ln143_reg_404_pp0_iter4_reg;
wire   [31:0] tmp_s_fu_245_p10;
reg   [3:0] i_8_fu_76;
wire   [3:0] add_ln143_fu_235_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i;
wire    ap_block_pp0_stage0;
reg   [31:0] D_inv_fu_80;
reg   [31:0] D_inv_1_fu_84;
reg   [31:0] D_inv_2_fu_88;
reg   [31:0] D_inv_3_fu_92;
reg   [31:0] D_inv_4_fu_96;
reg   [31:0] D_inv_5_fu_100;
reg   [31:0] D_inv_6_fu_104;
reg   [31:0] D_inv_7_fu_108;
wire    ap_block_pp0_stage0_01001;
wire   [2:0] tmp_s_fu_245_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_done_reg = 1'b0;
end

omp_reconstruction_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U1116(
    .din0(D),
    .din1(D_1),
    .din2(D_2),
    .din3(D_3),
    .din4(D_4),
    .din5(D_5),
    .din6(D_6),
    .din7(D_7),
    .din8(tmp_s_fu_245_p9),
    .dout(tmp_s_fu_245_p10)
);

omp_reconstruction_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln143_fu_229_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_8_fu_76 <= add_ln143_fu_235_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_8_fu_76 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln143_reg_404_pp0_iter4_reg == 3'd1))) begin
        D_inv_1_fu_84 <= grp_fu_3300_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln143_reg_404_pp0_iter4_reg == 3'd2))) begin
        D_inv_2_fu_88 <= grp_fu_3300_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln143_reg_404_pp0_iter4_reg == 3'd3))) begin
        D_inv_3_fu_92 <= grp_fu_3300_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln143_reg_404_pp0_iter4_reg == 3'd4))) begin
        D_inv_4_fu_96 <= grp_fu_3300_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln143_reg_404_pp0_iter4_reg == 3'd5))) begin
        D_inv_5_fu_100 <= grp_fu_3300_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln143_reg_404_pp0_iter4_reg == 3'd6))) begin
        D_inv_6_fu_104 <= grp_fu_3300_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln143_reg_404_pp0_iter4_reg == 3'd7))) begin
        D_inv_7_fu_108 <= grp_fu_3300_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln143_reg_404_pp0_iter4_reg == 3'd0))) begin
        D_inv_fu_80 <= grp_fu_3300_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln143_reg_400 <= icmp_ln143_fu_229_p2;
        icmp_ln143_reg_400_pp0_iter1_reg <= icmp_ln143_reg_400;
        trunc_ln143_reg_404_pp0_iter1_reg <= trunc_ln143_reg_404;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln143_reg_400_pp0_iter2_reg <= icmp_ln143_reg_400_pp0_iter1_reg;
        icmp_ln143_reg_400_pp0_iter3_reg <= icmp_ln143_reg_400_pp0_iter2_reg;
        trunc_ln143_reg_404_pp0_iter2_reg <= trunc_ln143_reg_404_pp0_iter1_reg;
        trunc_ln143_reg_404_pp0_iter3_reg <= trunc_ln143_reg_404_pp0_iter2_reg;
        trunc_ln143_reg_404_pp0_iter4_reg <= trunc_ln143_reg_404_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln143_fu_229_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln143_reg_404 <= trunc_ln143_fu_241_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln143_reg_400_pp0_iter3_reg == 1'd1))) begin
        D_inv_1_out_ap_vld = 1'b1;
    end else begin
        D_inv_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln143_reg_400_pp0_iter3_reg == 1'd1))) begin
        D_inv_2_out_ap_vld = 1'b1;
    end else begin
        D_inv_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln143_reg_400_pp0_iter3_reg == 1'd1))) begin
        D_inv_3_out_ap_vld = 1'b1;
    end else begin
        D_inv_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln143_reg_400_pp0_iter3_reg == 1'd1))) begin
        D_inv_4_out_ap_vld = 1'b1;
    end else begin
        D_inv_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln143_reg_400_pp0_iter3_reg == 1'd1))) begin
        D_inv_5_out_ap_vld = 1'b1;
    end else begin
        D_inv_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln143_reg_400_pp0_iter3_reg == 1'd1))) begin
        D_inv_6_out_ap_vld = 1'b1;
    end else begin
        D_inv_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln143_reg_400_pp0_iter3_reg == 1'd1))) begin
        D_inv_7_out_ap_vld = 1'b1;
    end else begin
        D_inv_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln143_reg_400_pp0_iter3_reg == 1'd1))) begin
        D_inv_out_ap_vld = 1'b1;
    end else begin
        D_inv_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln143_fu_229_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 4'd0;
    end else begin
        ap_sig_allocacmp_i = i_8_fu_76;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign D_inv_1_out = D_inv_1_fu_84;

assign D_inv_2_out = D_inv_2_fu_88;

assign D_inv_3_out = D_inv_3_fu_92;

assign D_inv_4_out = D_inv_4_fu_96;

assign D_inv_5_out = D_inv_5_fu_100;

assign D_inv_6_out = D_inv_6_fu_104;

assign D_inv_7_out = D_inv_7_fu_108;

assign D_inv_out = D_inv_fu_80;

assign add_ln143_fu_235_p2 = (ap_sig_allocacmp_i + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_3300_p_ce = 1'b1;

assign grp_fu_3300_p_din0 = 32'd1065353216;

assign grp_fu_3300_p_din1 = tmp_s_fu_245_p10;

assign icmp_ln143_fu_229_p2 = ((ap_sig_allocacmp_i == 4'd8) ? 1'b1 : 1'b0);

assign tmp_s_fu_245_p9 = ap_sig_allocacmp_i[2:0];

assign trunc_ln143_fu_241_p1 = ap_sig_allocacmp_i[2:0];

endmodule //omp_reconstruction_acd_inversion_Pipeline_inv_d_loop
